`include "cmos.v"
/* Generated by Yosys 0.8+500 (git sha1 49d641d9, clang 6.0.0-1ubuntu2 -fPIC -Os) */

(* src = "Byte_un_striping_estr.v:1" *)
module Byte_un_striping_estr(clk_f, clk_2f, lane_0, lane_1, valid_0, valid_1, reset, data_out_c, valid_out_c);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  (* src = "Byte_un_striping_estr.v:3" *)
  input clk_2f;
  (* src = "Byte_un_striping_estr.v:2" *)
  input clk_f;
  (* src = "Byte_un_striping_estr.v:9" *)
  output [7:0] data_out_c;
  (* onehot = 32'd1 *)
  wire [2:0] estado;
  (* src = "Byte_un_striping_estr.v:4" *)
  input [7:0] lane_0;
  (* src = "Byte_un_striping_estr.v:5" *)
  input [7:0] lane_1;
  (* src = "Byte_un_striping_estr.v:13" *)
  (* unused_bits = "0 1 2" *)
  wire [2:0] prox_estado;
  (* src = "Byte_un_striping_estr.v:8" *)
  input reset;
  (* src = "Byte_un_striping_estr.v:6" *)
  input valid_0;
  (* src = "Byte_un_striping_estr.v:7" *)
  input valid_1;
  (* src = "Byte_un_striping_estr.v:10" *)
  output valid_out_c;
  NOT _32_ (
    .A(valid_1),
    .Y(_03_)
  );
  NOT _33_ (
    .A(estado[2]),
    .Y(_04_)
  );
  NOT _34_ (
    .A(valid_0),
    .Y(_05_)
  );
  NOT _35_ (
    .A(reset),
    .Y(_06_)
  );
  NOR _36_ (
    .A(estado[1]),
    .B(estado[0]),
    .Y(_07_)
  );
  NOR _37_ (
    .A(valid_0),
    .B(_07_),
    .Y(_08_)
  );
  NAND _38_ (
    .A(_03_),
    .B(estado[2]),
    .Y(_09_)
  );
  NOR _39_ (
    .A(_06_),
    .B(_08_),
    .Y(_10_)
  );
  NAND _40_ (
    .A(_09_),
    .B(_10_),
    .Y(_02_)
  );
  NOR _41_ (
    .A(_03_),
    .B(_04_),
    .Y(_11_)
  );
  NAND _42_ (
    .A(lane_1[0]),
    .B(_11_),
    .Y(_12_)
  );
  NOR _43_ (
    .A(_05_),
    .B(_07_),
    .Y(_13_)
  );
  NAND _44_ (
    .A(lane_0[0]),
    .B(_13_),
    .Y(_14_)
  );
  NAND _45_ (
    .A(_12_),
    .B(_14_),
    .Y(data_out_c[0])
  );
  NAND _46_ (
    .A(lane_1[1]),
    .B(_11_),
    .Y(_15_)
  );
  NAND _47_ (
    .A(lane_0[1]),
    .B(_13_),
    .Y(_16_)
  );
  NAND _48_ (
    .A(_15_),
    .B(_16_),
    .Y(data_out_c[1])
  );
  NAND _49_ (
    .A(lane_1[2]),
    .B(_11_),
    .Y(_17_)
  );
  NAND _50_ (
    .A(lane_0[2]),
    .B(_13_),
    .Y(_18_)
  );
  NAND _51_ (
    .A(_17_),
    .B(_18_),
    .Y(data_out_c[2])
  );
  NAND _52_ (
    .A(lane_1[3]),
    .B(_11_),
    .Y(_19_)
  );
  NAND _53_ (
    .A(lane_0[3]),
    .B(_13_),
    .Y(_20_)
  );
  NAND _54_ (
    .A(_19_),
    .B(_20_),
    .Y(data_out_c[3])
  );
  NAND _55_ (
    .A(lane_1[4]),
    .B(_11_),
    .Y(_21_)
  );
  NAND _56_ (
    .A(lane_0[4]),
    .B(_13_),
    .Y(_22_)
  );
  NAND _57_ (
    .A(_21_),
    .B(_22_),
    .Y(data_out_c[4])
  );
  NAND _58_ (
    .A(lane_1[5]),
    .B(_11_),
    .Y(_23_)
  );
  NAND _59_ (
    .A(lane_0[5]),
    .B(_13_),
    .Y(_24_)
  );
  NAND _60_ (
    .A(_23_),
    .B(_24_),
    .Y(data_out_c[5])
  );
  NAND _61_ (
    .A(lane_1[6]),
    .B(_11_),
    .Y(_25_)
  );
  NAND _62_ (
    .A(lane_0[6]),
    .B(_13_),
    .Y(_26_)
  );
  NAND _63_ (
    .A(_25_),
    .B(_26_),
    .Y(data_out_c[6])
  );
  NAND _64_ (
    .A(lane_1[7]),
    .B(_11_),
    .Y(_27_)
  );
  NAND _65_ (
    .A(lane_0[7]),
    .B(_13_),
    .Y(_28_)
  );
  NAND _66_ (
    .A(_27_),
    .B(_28_),
    .Y(data_out_c[7])
  );
  NOR _67_ (
    .A(_11_),
    .B(_13_),
    .Y(_29_)
  );
  NOT _68_ (
    .A(_29_),
    .Y(valid_out_c)
  );
  NAND _69_ (
    .A(reset),
    .B(_11_),
    .Y(_30_)
  );
  NOT _70_ (
    .A(_30_),
    .Y(_00_)
  );
  NAND _71_ (
    .A(reset),
    .B(_13_),
    .Y(_31_)
  );
  NOT _72_ (
    .A(_31_),
    .Y(_01_)
  );
  DFF _73_ (
    .C(clk_2f),
    .D(_02_),
    .Q(estado[0])
  );
  DFF _74_ (
    .C(clk_2f),
    .D(_00_),
    .Q(estado[1])
  );
  DFF _75_ (
    .C(clk_2f),
    .D(_01_),
    .Q(estado[2])
  );
endmodule

(* src = "Serie_Paralelo_estr.v:2" *)
module Serie_Paralelo_estr(clk_8f, clk_f, data_in, reset, valid_out_c, parallel_out_c);
  (* src = "Serie_Paralelo_estr.v:44" *)
  wire [2:0] _000_;
  (* src = "Serie_Paralelo_estr.v:44" *)
  wire [7:0] _001_;
  (* src = "Serie_Paralelo_estr.v:44" *)
  wire [2:0] _002_;
  (* src = "Serie_Paralelo_estr.v:31" *)
  (* unused_bits = "0" *)
  wire [7:0] _003_;
  (* src = "Serie_Paralelo_estr.v:31" *)
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  (* src = "Serie_Paralelo_estr.v:12" *)
  wire [2:0] BC_counter;
  (* src = "Serie_Paralelo_estr.v:11" *)
  wire [7:0] Data_P;
  (* src = "Serie_Paralelo_estr.v:14" *)
  (* unused_bits = "0" *)
  wire active;
  (* src = "Serie_Paralelo_estr.v:12" *)
  wire [2:0] bit_counter;
  (* src = "Serie_Paralelo_estr.v:2" *)
  input clk_8f;
  (* src = "Serie_Paralelo_estr.v:3" *)
  input clk_f;
  (* src = "Serie_Paralelo_estr.v:4" *)
  input data_in;
  (* src = "Serie_Paralelo_estr.v:61" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] i;
  (* src = "Serie_Paralelo_estr.v:11" *)
  (* unused_bits = "0" *)
  wire [7:0] parallel_out_auxiliar;
  (* src = "Serie_Paralelo_estr.v:7" *)
  output [7:0] parallel_out_c;
  (* src = "Serie_Paralelo_estr.v:5" *)
  input reset;
  (* src = "Serie_Paralelo_estr.v:6" *)
  output valid_out_c;
  (* src = "Serie_Paralelo_estr.v:14" *)
  wire valid_out_c_retrasado;
  NOT _100_ (
    .A(bit_counter[2]),
    .Y(_059_)
  );
  NOT _101_ (
    .A(bit_counter[0]),
    .Y(_060_)
  );
  NOT _102_ (
    .A(Data_P[0]),
    .Y(_061_)
  );
  NOT _103_ (
    .A(bit_counter[1]),
    .Y(_062_)
  );
  NOT _104_ (
    .A(data_in),
    .Y(_063_)
  );
  NOT _105_ (
    .A(Data_P[2]),
    .Y(_064_)
  );
  NOT _106_ (
    .A(reset),
    .Y(_065_)
  );
  NOT _107_ (
    .A(BC_counter[0]),
    .Y(_066_)
  );
  NOT _108_ (
    .A(BC_counter[2]),
    .Y(_067_)
  );
  NOT _109_ (
    .A(Data_P[3]),
    .Y(_068_)
  );
  NOT _110_ (
    .A(Data_P[4]),
    .Y(_069_)
  );
  NOT _111_ (
    .A(Data_P[5]),
    .Y(_070_)
  );
  NOT _112_ (
    .A(Data_P[7]),
    .Y(_071_)
  );
  NAND _113_ (
    .A(_060_),
    .B(bit_counter[1]),
    .Y(_072_)
  );
  NOR _114_ (
    .A(bit_counter[2]),
    .B(_072_),
    .Y(_073_)
  );
  NOR _115_ (
    .A(Data_P[2]),
    .B(_073_),
    .Y(_074_)
  );
  NAND _116_ (
    .A(_063_),
    .B(_073_),
    .Y(_075_)
  );
  NAND _117_ (
    .A(reset),
    .B(_075_),
    .Y(_076_)
  );
  NOR _118_ (
    .A(_074_),
    .B(_076_),
    .Y(_001_[2])
  );
  NAND _119_ (
    .A(bit_counter[0]),
    .B(_062_),
    .Y(_077_)
  );
  NOR _120_ (
    .A(bit_counter[2]),
    .B(_077_),
    .Y(_078_)
  );
  NOR _121_ (
    .A(Data_P[1]),
    .B(_078_),
    .Y(_079_)
  );
  NAND _122_ (
    .A(_063_),
    .B(_078_),
    .Y(_080_)
  );
  NAND _123_ (
    .A(reset),
    .B(_080_),
    .Y(_081_)
  );
  NOR _124_ (
    .A(_079_),
    .B(_081_),
    .Y(_001_[1])
  );
  NOR _125_ (
    .A(bit_counter[0]),
    .B(bit_counter[1]),
    .Y(_082_)
  );
  NAND _126_ (
    .A(_060_),
    .B(_062_),
    .Y(_083_)
  );
  NOR _127_ (
    .A(bit_counter[2]),
    .B(_083_),
    .Y(_084_)
  );
  NAND _128_ (
    .A(_063_),
    .B(_084_),
    .Y(_085_)
  );
  NAND _129_ (
    .A(reset),
    .B(_085_),
    .Y(_086_)
  );
  NOR _130_ (
    .A(Data_P[0]),
    .B(_084_),
    .Y(_087_)
  );
  NOR _131_ (
    .A(_086_),
    .B(_087_),
    .Y(_001_[0])
  );
  NAND _132_ (
    .A(Data_P[3]),
    .B(Data_P[4]),
    .Y(_088_)
  );
  NAND _133_ (
    .A(Data_P[5]),
    .B(Data_P[7]),
    .Y(_089_)
  );
  NOR _134_ (
    .A(_088_),
    .B(_089_),
    .Y(_090_)
  );
  NOT _135_ (
    .A(_090_),
    .Y(_091_)
  );
  NOR _136_ (
    .A(Data_P[0]),
    .B(Data_P[1]),
    .Y(_092_)
  );
  NOR _137_ (
    .A(Data_P[6]),
    .B(_064_),
    .Y(_093_)
  );
  NAND _138_ (
    .A(_092_),
    .B(_093_),
    .Y(_094_)
  );
  NOR _139_ (
    .A(_091_),
    .B(_094_),
    .Y(_095_)
  );
  NOT _140_ (
    .A(_095_),
    .Y(_096_)
  );
  NAND _141_ (
    .A(_084_),
    .B(_095_),
    .Y(_097_)
  );
  NOR _142_ (
    .A(_066_),
    .B(_097_),
    .Y(_098_)
  );
  NAND _143_ (
    .A(_066_),
    .B(_097_),
    .Y(_099_)
  );
  NAND _144_ (
    .A(reset),
    .B(_099_),
    .Y(_005_)
  );
  NOR _145_ (
    .A(_098_),
    .B(_005_),
    .Y(_000_[0])
  );
  NAND _146_ (
    .A(BC_counter[1]),
    .B(_098_),
    .Y(_006_)
  );
  NOT _147_ (
    .A(_006_),
    .Y(_007_)
  );
  NOR _148_ (
    .A(BC_counter[1]),
    .B(_098_),
    .Y(_008_)
  );
  NOT _149_ (
    .A(_008_),
    .Y(_009_)
  );
  NAND _150_ (
    .A(reset),
    .B(_009_),
    .Y(_010_)
  );
  NOR _151_ (
    .A(_007_),
    .B(_010_),
    .Y(_000_[1])
  );
  NOR _152_ (
    .A(_067_),
    .B(_006_),
    .Y(_011_)
  );
  NAND _153_ (
    .A(_067_),
    .B(_006_),
    .Y(_012_)
  );
  NAND _154_ (
    .A(reset),
    .B(_012_),
    .Y(_013_)
  );
  NOR _155_ (
    .A(_011_),
    .B(_013_),
    .Y(_000_[2])
  );
  NAND _156_ (
    .A(BC_counter[2]),
    .B(_096_),
    .Y(_014_)
  );
  NOT _157_ (
    .A(_014_),
    .Y(_004_)
  );
  NAND _158_ (
    .A(Data_P[1]),
    .B(BC_counter[2]),
    .Y(_015_)
  );
  NOT _159_ (
    .A(_015_),
    .Y(_003_[1])
  );
  NOR _160_ (
    .A(_064_),
    .B(_014_),
    .Y(_003_[2])
  );
  NOR _161_ (
    .A(_068_),
    .B(_014_),
    .Y(_003_[3])
  );
  NOR _162_ (
    .A(_069_),
    .B(_014_),
    .Y(_003_[4])
  );
  NOR _163_ (
    .A(_070_),
    .B(_014_),
    .Y(_003_[5])
  );
  NAND _164_ (
    .A(Data_P[6]),
    .B(BC_counter[2]),
    .Y(_016_)
  );
  NOT _165_ (
    .A(_016_),
    .Y(_003_[6])
  );
  NOR _166_ (
    .A(_071_),
    .B(_014_),
    .Y(_003_[7])
  );
  NAND _167_ (
    .A(bit_counter[0]),
    .B(reset),
    .Y(_002_[0])
  );
  NAND _168_ (
    .A(bit_counter[0]),
    .B(bit_counter[1]),
    .Y(_017_)
  );
  NOR _169_ (
    .A(_065_),
    .B(_082_),
    .Y(_018_)
  );
  NAND _170_ (
    .A(_017_),
    .B(_018_),
    .Y(_002_[1])
  );
  NAND _171_ (
    .A(bit_counter[2]),
    .B(_083_),
    .Y(_019_)
  );
  NOR _172_ (
    .A(_065_),
    .B(_084_),
    .Y(_020_)
  );
  NAND _173_ (
    .A(_019_),
    .B(_020_),
    .Y(_002_[2])
  );
  NAND _174_ (
    .A(reset),
    .B(parallel_out_auxiliar[7]),
    .Y(_021_)
  );
  NOT _175_ (
    .A(_021_),
    .Y(parallel_out_c[7])
  );
  NAND _176_ (
    .A(reset),
    .B(BC_counter[2]),
    .Y(_022_)
  );
  NOT _177_ (
    .A(_022_),
    .Y(_023_)
  );
  NAND _178_ (
    .A(valid_out_c_retrasado),
    .B(_023_),
    .Y(_024_)
  );
  NAND _179_ (
    .A(parallel_out_auxiliar[4]),
    .B(parallel_out_auxiliar[2]),
    .Y(_025_)
  );
  NAND _180_ (
    .A(parallel_out_auxiliar[3]),
    .B(parallel_out_auxiliar[5]),
    .Y(_026_)
  );
  NOR _181_ (
    .A(_025_),
    .B(_026_),
    .Y(_027_)
  );
  NAND _182_ (
    .A(_061_),
    .B(_027_),
    .Y(_028_)
  );
  NOR _183_ (
    .A(parallel_out_auxiliar[1]),
    .B(parallel_out_auxiliar[6]),
    .Y(_029_)
  );
  NAND _184_ (
    .A(parallel_out_auxiliar[7]),
    .B(_029_),
    .Y(_030_)
  );
  NOR _185_ (
    .A(_028_),
    .B(_030_),
    .Y(_031_)
  );
  NOR _186_ (
    .A(_024_),
    .B(_031_),
    .Y(valid_out_c)
  );
  NAND _187_ (
    .A(parallel_out_auxiliar[1]),
    .B(reset),
    .Y(_032_)
  );
  NOT _188_ (
    .A(_032_),
    .Y(parallel_out_c[1])
  );
  NAND _189_ (
    .A(Data_P[0]),
    .B(reset),
    .Y(_033_)
  );
  NOT _190_ (
    .A(_033_),
    .Y(parallel_out_c[0])
  );
  NAND _191_ (
    .A(reset),
    .B(parallel_out_auxiliar[4]),
    .Y(_034_)
  );
  NOT _192_ (
    .A(_034_),
    .Y(parallel_out_c[4])
  );
  NAND _193_ (
    .A(reset),
    .B(parallel_out_auxiliar[2]),
    .Y(_035_)
  );
  NOT _194_ (
    .A(_035_),
    .Y(parallel_out_c[2])
  );
  NAND _195_ (
    .A(reset),
    .B(parallel_out_auxiliar[3]),
    .Y(_036_)
  );
  NOT _196_ (
    .A(_036_),
    .Y(parallel_out_c[3])
  );
  NAND _197_ (
    .A(reset),
    .B(parallel_out_auxiliar[5]),
    .Y(_037_)
  );
  NOT _198_ (
    .A(_037_),
    .Y(parallel_out_c[5])
  );
  NAND _199_ (
    .A(parallel_out_auxiliar[6]),
    .B(reset),
    .Y(_038_)
  );
  NOT _200_ (
    .A(_038_),
    .Y(parallel_out_c[6])
  );
  NOR _201_ (
    .A(_059_),
    .B(_017_),
    .Y(_039_)
  );
  NOR _202_ (
    .A(Data_P[7]),
    .B(_039_),
    .Y(_040_)
  );
  NAND _203_ (
    .A(_063_),
    .B(_039_),
    .Y(_041_)
  );
  NAND _204_ (
    .A(reset),
    .B(_041_),
    .Y(_042_)
  );
  NOR _205_ (
    .A(_040_),
    .B(_042_),
    .Y(_001_[7])
  );
  NOR _206_ (
    .A(_059_),
    .B(_072_),
    .Y(_043_)
  );
  NOR _207_ (
    .A(Data_P[6]),
    .B(_043_),
    .Y(_044_)
  );
  NAND _208_ (
    .A(_063_),
    .B(_043_),
    .Y(_045_)
  );
  NAND _209_ (
    .A(reset),
    .B(_045_),
    .Y(_046_)
  );
  NOR _210_ (
    .A(_044_),
    .B(_046_),
    .Y(_001_[6])
  );
  NOR _211_ (
    .A(_059_),
    .B(_077_),
    .Y(_047_)
  );
  NOR _212_ (
    .A(Data_P[5]),
    .B(_047_),
    .Y(_048_)
  );
  NAND _213_ (
    .A(_063_),
    .B(_047_),
    .Y(_049_)
  );
  NAND _214_ (
    .A(reset),
    .B(_049_),
    .Y(_050_)
  );
  NOR _215_ (
    .A(_048_),
    .B(_050_),
    .Y(_001_[5])
  );
  NAND _216_ (
    .A(bit_counter[2]),
    .B(_082_),
    .Y(_051_)
  );
  NAND _217_ (
    .A(_069_),
    .B(_051_),
    .Y(_052_)
  );
  NOR _218_ (
    .A(data_in),
    .B(_051_),
    .Y(_053_)
  );
  NAND _219_ (
    .A(reset),
    .B(_052_),
    .Y(_054_)
  );
  NOR _220_ (
    .A(_053_),
    .B(_054_),
    .Y(_001_[4])
  );
  NOR _221_ (
    .A(bit_counter[2]),
    .B(_017_),
    .Y(_055_)
  );
  NOR _222_ (
    .A(Data_P[3]),
    .B(_055_),
    .Y(_056_)
  );
  NAND _223_ (
    .A(_063_),
    .B(_055_),
    .Y(_057_)
  );
  NAND _224_ (
    .A(reset),
    .B(_057_),
    .Y(_058_)
  );
  NOR _225_ (
    .A(_056_),
    .B(_058_),
    .Y(_001_[3])
  );
  (* src = "Serie_Paralelo_estr.v:44" *)
  DFF _226_ (
    .C(clk_8f),
    .D(_002_[0]),
    .Q(bit_counter[0])
  );
  (* src = "Serie_Paralelo_estr.v:44" *)
  DFF _227_ (
    .C(clk_8f),
    .D(_002_[1]),
    .Q(bit_counter[1])
  );
  (* src = "Serie_Paralelo_estr.v:44" *)
  DFF _228_ (
    .C(clk_8f),
    .D(_002_[2]),
    .Q(bit_counter[2])
  );
  (* src = "Serie_Paralelo_estr.v:44" *)
  DFF _229_ (
    .C(clk_8f),
    .D(_000_[0]),
    .Q(BC_counter[0])
  );
  (* src = "Serie_Paralelo_estr.v:44" *)
  DFF _230_ (
    .C(clk_8f),
    .D(_000_[1]),
    .Q(BC_counter[1])
  );
  (* src = "Serie_Paralelo_estr.v:44" *)
  DFF _231_ (
    .C(clk_8f),
    .D(_000_[2]),
    .Q(BC_counter[2])
  );
  (* src = "Serie_Paralelo_estr.v:44" *)
  DFF _232_ (
    .C(clk_8f),
    .D(_001_[0]),
    .Q(Data_P[0])
  );
  (* src = "Serie_Paralelo_estr.v:44" *)
  DFF _233_ (
    .C(clk_8f),
    .D(_001_[1]),
    .Q(Data_P[1])
  );
  (* src = "Serie_Paralelo_estr.v:44" *)
  DFF _234_ (
    .C(clk_8f),
    .D(_001_[2]),
    .Q(Data_P[2])
  );
  (* src = "Serie_Paralelo_estr.v:44" *)
  DFF _235_ (
    .C(clk_8f),
    .D(_001_[3]),
    .Q(Data_P[3])
  );
  (* src = "Serie_Paralelo_estr.v:44" *)
  DFF _236_ (
    .C(clk_8f),
    .D(_001_[4]),
    .Q(Data_P[4])
  );
  (* src = "Serie_Paralelo_estr.v:44" *)
  DFF _237_ (
    .C(clk_8f),
    .D(_001_[5]),
    .Q(Data_P[5])
  );
  (* src = "Serie_Paralelo_estr.v:44" *)
  DFF _238_ (
    .C(clk_8f),
    .D(_001_[6]),
    .Q(Data_P[6])
  );
  (* src = "Serie_Paralelo_estr.v:44" *)
  DFF _239_ (
    .C(clk_8f),
    .D(_001_[7]),
    .Q(Data_P[7])
  );
  (* src = "Serie_Paralelo_estr.v:31" *)
  DFF _240_ (
    .C(clk_f),
    .D(_003_[1]),
    .Q(parallel_out_auxiliar[1])
  );
  (* src = "Serie_Paralelo_estr.v:31" *)
  DFF _241_ (
    .C(clk_f),
    .D(_003_[2]),
    .Q(parallel_out_auxiliar[2])
  );
  (* src = "Serie_Paralelo_estr.v:31" *)
  DFF _242_ (
    .C(clk_f),
    .D(_003_[3]),
    .Q(parallel_out_auxiliar[3])
  );
  (* src = "Serie_Paralelo_estr.v:31" *)
  DFF _243_ (
    .C(clk_f),
    .D(_003_[4]),
    .Q(parallel_out_auxiliar[4])
  );
  (* src = "Serie_Paralelo_estr.v:31" *)
  DFF _244_ (
    .C(clk_f),
    .D(_003_[5]),
    .Q(parallel_out_auxiliar[5])
  );
  (* src = "Serie_Paralelo_estr.v:31" *)
  DFF _245_ (
    .C(clk_f),
    .D(_003_[6]),
    .Q(parallel_out_auxiliar[6])
  );
  (* src = "Serie_Paralelo_estr.v:31" *)
  DFF _246_ (
    .C(clk_f),
    .D(_003_[7]),
    .Q(parallel_out_auxiliar[7])
  );
  (* src = "Serie_Paralelo_estr.v:31" *)
  DFF _247_ (
    .C(clk_f),
    .D(_004_),
    .Q(valid_out_c_retrasado)
  );
endmodule

(* src = "demux_estr.v:1" *)
module demux_estr(data_out_0_c, valid_out_0_c, data_out_1_c, valid_out_1_c, data_in_c, valid_in_c, reset, clk2f, clk8f);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  (* src = "demux_estr.v:9" *)
  input clk2f;
  (* src = "demux_estr.v:10" *)
  input clk8f;
  (* src = "demux_estr.v:6" *)
  input [7:0] data_in_c;
  (* src = "demux_estr.v:2" *)
  output [7:0] data_out_0_c;
  (* src = "demux_estr.v:4" *)
  output [7:0] data_out_1_c;
  (* src = "demux_estr.v:12" *)
  (* unused_bits = "0 1 2 3 4 5" *)
  wire [5:0] nxt_st;
  (* src = "demux_estr.v:8" *)
  input reset;
  (* src = "demux_estr.v:13" *)
  wire reset2;
  (* src = "demux_estr.v:13" *)
  wire resetm;
  (* onehot = 32'd1 *)
  wire [5:0] st;
  (* src = "demux_estr.v:7" *)
  input valid_in_c;
  (* src = "demux_estr.v:3" *)
  output valid_out_0_c;
  (* src = "demux_estr.v:5" *)
  output valid_out_1_c;
  NOT _32_ (
    .A(reset),
    .Y(_06_)
  );
  NOT _33_ (
    .A(valid_in_c),
    .Y(_07_)
  );
  NOT _34_ (
    .A(st[4]),
    .Y(_08_)
  );
  NOT _35_ (
    .A(data_in_c[0]),
    .Y(_09_)
  );
  NOT _36_ (
    .A(data_in_c[1]),
    .Y(_10_)
  );
  NOT _37_ (
    .A(data_in_c[2]),
    .Y(_11_)
  );
  NOT _38_ (
    .A(data_in_c[3]),
    .Y(_12_)
  );
  NOT _39_ (
    .A(data_in_c[4]),
    .Y(_13_)
  );
  NOT _40_ (
    .A(data_in_c[5]),
    .Y(_14_)
  );
  NOT _41_ (
    .A(data_in_c[6]),
    .Y(_15_)
  );
  NOT _42_ (
    .A(data_in_c[7]),
    .Y(_16_)
  );
  NOT _43_ (
    .A(reset2),
    .Y(_17_)
  );
  NOR _44_ (
    .A(_06_),
    .B(_17_),
    .Y(_18_)
  );
  NAND _45_ (
    .A(_06_),
    .B(st[0]),
    .Y(_19_)
  );
  NAND _46_ (
    .A(reset2),
    .B(_19_),
    .Y(_04_)
  );
  NAND _47_ (
    .A(st[0]),
    .B(_18_),
    .Y(_20_)
  );
  NOR _48_ (
    .A(valid_in_c),
    .B(_17_),
    .Y(_21_)
  );
  NAND _49_ (
    .A(_07_),
    .B(reset2),
    .Y(_22_)
  );
  NAND _50_ (
    .A(st[5]),
    .B(_21_),
    .Y(_23_)
  );
  NAND _51_ (
    .A(_20_),
    .B(_23_),
    .Y(_05_)
  );
  NOR _52_ (
    .A(st[3]),
    .B(st[1]),
    .Y(_24_)
  );
  NOT _53_ (
    .A(_24_),
    .Y(_25_)
  );
  NAND _54_ (
    .A(valid_in_c),
    .B(_25_),
    .Y(_26_)
  );
  NOT _55_ (
    .A(_26_),
    .Y(valid_out_1_c)
  );
  NOR _56_ (
    .A(_09_),
    .B(_26_),
    .Y(data_out_1_c[0])
  );
  NOR _57_ (
    .A(_10_),
    .B(_26_),
    .Y(data_out_1_c[1])
  );
  NOR _58_ (
    .A(_11_),
    .B(_26_),
    .Y(data_out_1_c[2])
  );
  NOR _59_ (
    .A(_12_),
    .B(_26_),
    .Y(data_out_1_c[3])
  );
  NOR _60_ (
    .A(_13_),
    .B(_26_),
    .Y(data_out_1_c[4])
  );
  NOR _61_ (
    .A(_14_),
    .B(_26_),
    .Y(data_out_1_c[5])
  );
  NOR _62_ (
    .A(_15_),
    .B(_26_),
    .Y(data_out_1_c[6])
  );
  NOR _63_ (
    .A(_16_),
    .B(_26_),
    .Y(data_out_1_c[7])
  );
  NOR _64_ (
    .A(st[2]),
    .B(st[5]),
    .Y(_27_)
  );
  NAND _65_ (
    .A(_08_),
    .B(_27_),
    .Y(_28_)
  );
  NAND _66_ (
    .A(valid_in_c),
    .B(_28_),
    .Y(_29_)
  );
  NOT _67_ (
    .A(_29_),
    .Y(valid_out_0_c)
  );
  NOR _68_ (
    .A(_09_),
    .B(_29_),
    .Y(data_out_0_c[0])
  );
  NOR _69_ (
    .A(_10_),
    .B(_29_),
    .Y(data_out_0_c[1])
  );
  NOR _70_ (
    .A(_11_),
    .B(_29_),
    .Y(data_out_0_c[2])
  );
  NOR _71_ (
    .A(_12_),
    .B(_29_),
    .Y(data_out_0_c[3])
  );
  NOR _72_ (
    .A(_13_),
    .B(_29_),
    .Y(data_out_0_c[4])
  );
  NOR _73_ (
    .A(_14_),
    .B(_29_),
    .Y(data_out_0_c[5])
  );
  NOR _74_ (
    .A(_15_),
    .B(_29_),
    .Y(data_out_0_c[6])
  );
  NOR _75_ (
    .A(_16_),
    .B(_29_),
    .Y(data_out_0_c[7])
  );
  NOR _76_ (
    .A(st[3]),
    .B(st[2]),
    .Y(_30_)
  );
  NOR _77_ (
    .A(_22_),
    .B(_30_),
    .Y(_01_)
  );
  NOR _78_ (
    .A(_17_),
    .B(_29_),
    .Y(_03_)
  );
  NOR _79_ (
    .A(_17_),
    .B(_26_),
    .Y(_02_)
  );
  NOR _80_ (
    .A(st[4]),
    .B(st[1]),
    .Y(_31_)
  );
  NOR _81_ (
    .A(_22_),
    .B(_31_),
    .Y(_00_)
  );
  DFF _82_ (
    .C(clk2f),
    .D(_04_),
    .Q(st[0])
  );
  DFF _83_ (
    .C(clk2f),
    .D(_00_),
    .Q(st[1])
  );
  DFF _84_ (
    .C(clk2f),
    .D(_01_),
    .Q(st[2])
  );
  DFF _85_ (
    .C(clk2f),
    .D(_02_),
    .Q(st[3])
  );
  DFF _86_ (
    .C(clk2f),
    .D(_03_),
    .Q(st[4])
  );
  DFF _87_ (
    .C(clk2f),
    .D(_05_),
    .Q(st[5])
  );
  (* src = "demux_estr.v:23" *)
  DFF _88_ (
    .C(clk8f),
    .D(resetm),
    .Q(reset2)
  );
  (* src = "demux_estr.v:23" *)
  DFF _89_ (
    .C(clk8f),
    .D(reset),
    .Q(resetm)
  );
endmodule

(* top =  1  *)
(* src = "phy_rx_cond.v:5" *)
module phy_rx_estr(data_in_c_0, data_in_c_1, clk_f, clk_2f, clk_8f, reset, data_out_e_0, data_out_e_1, valid_out_e_0, valid_out_e_1);
  (* src = "phy_rx_cond.v:9" *)
  input clk_2f;
  (* src = "phy_rx_cond.v:10" *)
  input clk_8f;
  (* src = "phy_rx_cond.v:8" *)
  input clk_f;
  (* src = "phy_rx_cond.v:51" *)
  wire clk_nf;
  (* src = "phy_rx_cond.v:6" *)
  input data_in_c_0;
  (* src = "phy_rx_cond.v:7" *)
  input data_in_c_1;
  (* src = "phy_rx_cond.v:12" *)
  output [7:0] data_out_e_0;
  (* src = "phy_rx_cond.v:13" *)
  output [7:0] data_out_e_1;
  (* src = "phy_rx_cond.v:45" *)
  wire [7:0] data_out_c_US;
  (* src = "phy_rx_cond.v:46" *)
  wire [7:0] lane_c_0;
  (* src = "phy_rx_cond.v:47" *)
  wire [7:0] lane_c_1;
  (* src = "phy_rx_cond.v:11" *)
  input reset;
  (* src = "phy_rx_cond.v:54" *)
  wire reset0;
  (* src = "phy_rx_cond.v:55" *)
  wire reset1;
  (* src = "phy_rx_cond.v:48" *)
  wire valid_c_0_SP;
  (* src = "phy_rx_cond.v:49" *)
  wire valid_c_1_SP;
  (* src = "phy_rx_cond.v:14" *)
  output valid_out_e_0;
  (* src = "phy_rx_cond.v:15" *)
  output valid_out_e_1;
  (* src = "phy_rx_cond.v:50" *)
  wire valid_out_c_US;
  NOT _0_ (
    .A(clk_f),
    .Y(clk_nf)
  );
  (* src = "phy_rx_cond.v:58" *)
  DFF _1_ (
    .C(clk_2f),
    .D(reset),
    .Q(reset1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_rx_cond.v:99" *)
  Byte_un_striping_estr Byte_un_striping_instance0 (
    .clk_2f(clk_2f),
    .clk_f(clk_f),
    .data_out_c(data_out_c_US),
    .lane_0(lane_c_0),
    .lane_1(lane_c_1),
    .reset(reset),
    .valid_0(valid_c_0_SP),
    .valid_1(valid_c_1_SP),
    .valid_out_c(valid_out_c_US)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_rx_cond.v:76" *)
  Serie_Paralelo_estr Serie_Paralelo_estr_instance0 (
    .clk_8f(clk_8f),
    .clk_f(clk_f),
    .data_in(data_in_c_0),
    .parallel_out_c(lane_c_0),
    .reset(reset),
    .valid_out_c(valid_c_0_SP)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_rx_cond.v:86" *)
  Serie_Paralelo_estr Serie_Paralelo_estr_instance1 (
    .clk_8f(clk_8f),
    .clk_f(clk_nf),
    .data_in(data_in_c_1),
    .parallel_out_c(lane_c_1),
    .reset(reset1),
    .valid_out_c(valid_c_1_SP)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_rx_cond.v:114" *)
  demux_estr demux_estr_cond_instance0 (
    .clk2f(clk_2f),
    .clk8f(clk_8f),
    .data_in_c(data_out_c_US),
    .data_out_0_c(data_out_e_0),
    .data_out_1_c(data_out_e_1),
    .reset(reset),
    .valid_in_c(valid_out_c_US),
    .valid_out_0_c(valid_out_e_0),
    .valid_out_1_c(valid_out_e_1)
  );
  assign reset0 = reset;
endmodule
