`include "cmos.v"
/* Generated by Yosys 0.8+500 (git sha1 49d641d9, clang 6.0.0-1ubuntu2 -fPIC -Os) */

(* src = "./res/Byte_striping_estr.v:1" *)
module Byte_striping_estr(clk_2f, valid_in, data_in, reset, lane_0_c, lane_1_c, valid_0_c, valid_1_c);
  (* src = "./res/Byte_striping_estr.v:80" *)
  wire _000_;
  (* src = "./res/Byte_striping_estr.v:20" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  (* src = "./res/Byte_striping_estr.v:2" *)
  input clk_2f;
  (* src = "./res/Byte_striping_estr.v:4" *)
  input [7:0] data_in;
  (* src = "./res/Byte_striping_estr.v:6" *)
  output [7:0] lane_0_c;
  (* src = "./res/Byte_striping_estr.v:7" *)
  output [7:0] lane_1_c;
  (* src = "./res/Byte_striping_estr.v:5" *)
  input reset;
  (* src = "./res/Byte_striping_estr.v:12" *)
  wire selector;
  (* src = "./res/Byte_striping_estr.v:8" *)
  output valid_0_c;
  (* src = "./res/Byte_striping_estr.v:9" *)
  output valid_1_c;
  (* src = "./res/Byte_striping_estr.v:14" *)
  wire valid_atrasado;
  (* src = "./res/Byte_striping_estr.v:3" *)
  input valid_in;
  (* src = "./res/Byte_striping_estr.v:13" *)
  wire [7:0] y_0;
  (* src = "./res/Byte_striping_estr.v:13" *)
  wire [7:0] y_1;
  NOT _074_ (
    .A(data_in[0]),
    .Y(_035_)
  );
  NOT _075_ (
    .A(selector),
    .Y(_036_)
  );
  NOT _076_ (
    .A(data_in[1]),
    .Y(_037_)
  );
  NOT _077_ (
    .A(data_in[2]),
    .Y(_038_)
  );
  NOT _078_ (
    .A(data_in[3]),
    .Y(_039_)
  );
  NOT _079_ (
    .A(data_in[4]),
    .Y(_040_)
  );
  NOT _080_ (
    .A(data_in[5]),
    .Y(_041_)
  );
  NOT _081_ (
    .A(data_in[6]),
    .Y(_042_)
  );
  NOT _082_ (
    .A(data_in[7]),
    .Y(_043_)
  );
  NOT _083_ (
    .A(valid_in),
    .Y(_044_)
  );
  NOR _084_ (
    .A(selector),
    .B(_044_),
    .Y(_000_)
  );
  NOR _085_ (
    .A(y_0[0]),
    .B(_000_),
    .Y(_045_)
  );
  NAND _086_ (
    .A(_035_),
    .B(_000_),
    .Y(_046_)
  );
  NAND _087_ (
    .A(reset),
    .B(_046_),
    .Y(_047_)
  );
  NOR _088_ (
    .A(_045_),
    .B(_047_),
    .Y(lane_0_c[0])
  );
  NOR _089_ (
    .A(y_0[1]),
    .B(_000_),
    .Y(_048_)
  );
  NAND _090_ (
    .A(_037_),
    .B(_000_),
    .Y(_049_)
  );
  NAND _091_ (
    .A(reset),
    .B(_049_),
    .Y(_050_)
  );
  NOR _092_ (
    .A(_048_),
    .B(_050_),
    .Y(lane_0_c[1])
  );
  NOR _093_ (
    .A(y_0[2]),
    .B(_000_),
    .Y(_051_)
  );
  NAND _094_ (
    .A(_038_),
    .B(_000_),
    .Y(_052_)
  );
  NAND _095_ (
    .A(reset),
    .B(_052_),
    .Y(_053_)
  );
  NOR _096_ (
    .A(_051_),
    .B(_053_),
    .Y(lane_0_c[2])
  );
  NOR _097_ (
    .A(y_0[3]),
    .B(_000_),
    .Y(_054_)
  );
  NAND _098_ (
    .A(_039_),
    .B(_000_),
    .Y(_055_)
  );
  NAND _099_ (
    .A(reset),
    .B(_055_),
    .Y(_056_)
  );
  NOR _100_ (
    .A(_054_),
    .B(_056_),
    .Y(lane_0_c[3])
  );
  NOR _101_ (
    .A(y_0[4]),
    .B(_000_),
    .Y(_057_)
  );
  NAND _102_ (
    .A(_040_),
    .B(_000_),
    .Y(_058_)
  );
  NAND _103_ (
    .A(reset),
    .B(_058_),
    .Y(_059_)
  );
  NOR _104_ (
    .A(_057_),
    .B(_059_),
    .Y(lane_0_c[4])
  );
  NOR _105_ (
    .A(y_0[5]),
    .B(_000_),
    .Y(_060_)
  );
  NAND _106_ (
    .A(_041_),
    .B(_000_),
    .Y(_061_)
  );
  NAND _107_ (
    .A(reset),
    .B(_061_),
    .Y(_062_)
  );
  NOR _108_ (
    .A(_060_),
    .B(_062_),
    .Y(lane_0_c[5])
  );
  NOR _109_ (
    .A(y_0[6]),
    .B(_000_),
    .Y(_063_)
  );
  NAND _110_ (
    .A(_042_),
    .B(_000_),
    .Y(_064_)
  );
  NAND _111_ (
    .A(reset),
    .B(_064_),
    .Y(_065_)
  );
  NOR _112_ (
    .A(_063_),
    .B(_065_),
    .Y(lane_0_c[6])
  );
  NOR _113_ (
    .A(y_0[7]),
    .B(_000_),
    .Y(_066_)
  );
  NAND _114_ (
    .A(_043_),
    .B(_000_),
    .Y(_067_)
  );
  NAND _115_ (
    .A(reset),
    .B(_067_),
    .Y(_068_)
  );
  NOR _116_ (
    .A(_066_),
    .B(_068_),
    .Y(lane_0_c[7])
  );
  NAND _117_ (
    .A(valid_in),
    .B(reset),
    .Y(_069_)
  );
  NOT _118_ (
    .A(_069_),
    .Y(_001_)
  );
  NAND _119_ (
    .A(selector),
    .B(reset),
    .Y(_070_)
  );
  NAND _120_ (
    .A(_069_),
    .B(_070_),
    .Y(valid_0_c)
  );
  NOR _121_ (
    .A(_036_),
    .B(valid_in),
    .Y(_071_)
  );
  NAND _122_ (
    .A(valid_atrasado),
    .B(reset),
    .Y(_072_)
  );
  NOR _123_ (
    .A(_071_),
    .B(_072_),
    .Y(valid_1_c)
  );
  NOR _124_ (
    .A(_036_),
    .B(_044_),
    .Y(_073_)
  );
  NAND _125_ (
    .A(selector),
    .B(valid_in),
    .Y(_002_)
  );
  NOR _126_ (
    .A(y_1[0]),
    .B(_073_),
    .Y(_003_)
  );
  NOR _127_ (
    .A(data_in[0]),
    .B(_002_),
    .Y(_004_)
  );
  NOT _128_ (
    .A(_004_),
    .Y(_005_)
  );
  NAND _129_ (
    .A(reset),
    .B(_005_),
    .Y(_006_)
  );
  NOR _130_ (
    .A(_003_),
    .B(_006_),
    .Y(lane_1_c[0])
  );
  NOR _131_ (
    .A(y_1[1]),
    .B(_073_),
    .Y(_007_)
  );
  NOR _132_ (
    .A(data_in[1]),
    .B(_002_),
    .Y(_008_)
  );
  NOT _133_ (
    .A(_008_),
    .Y(_009_)
  );
  NAND _134_ (
    .A(reset),
    .B(_009_),
    .Y(_010_)
  );
  NOR _135_ (
    .A(_007_),
    .B(_010_),
    .Y(lane_1_c[1])
  );
  NOR _136_ (
    .A(y_1[2]),
    .B(_073_),
    .Y(_011_)
  );
  NOR _137_ (
    .A(data_in[2]),
    .B(_002_),
    .Y(_012_)
  );
  NOT _138_ (
    .A(_012_),
    .Y(_013_)
  );
  NAND _139_ (
    .A(reset),
    .B(_013_),
    .Y(_014_)
  );
  NOR _140_ (
    .A(_011_),
    .B(_014_),
    .Y(lane_1_c[2])
  );
  NOR _141_ (
    .A(y_1[3]),
    .B(_073_),
    .Y(_015_)
  );
  NOR _142_ (
    .A(data_in[3]),
    .B(_002_),
    .Y(_016_)
  );
  NOT _143_ (
    .A(_016_),
    .Y(_017_)
  );
  NAND _144_ (
    .A(reset),
    .B(_017_),
    .Y(_018_)
  );
  NOR _145_ (
    .A(_015_),
    .B(_018_),
    .Y(lane_1_c[3])
  );
  NOR _146_ (
    .A(y_1[4]),
    .B(_073_),
    .Y(_019_)
  );
  NOR _147_ (
    .A(data_in[4]),
    .B(_002_),
    .Y(_020_)
  );
  NOT _148_ (
    .A(_020_),
    .Y(_021_)
  );
  NAND _149_ (
    .A(reset),
    .B(_021_),
    .Y(_022_)
  );
  NOR _150_ (
    .A(_019_),
    .B(_022_),
    .Y(lane_1_c[4])
  );
  NOR _151_ (
    .A(y_1[5]),
    .B(_073_),
    .Y(_023_)
  );
  NOR _152_ (
    .A(data_in[5]),
    .B(_002_),
    .Y(_024_)
  );
  NOT _153_ (
    .A(_024_),
    .Y(_025_)
  );
  NAND _154_ (
    .A(reset),
    .B(_025_),
    .Y(_026_)
  );
  NOR _155_ (
    .A(_023_),
    .B(_026_),
    .Y(lane_1_c[5])
  );
  NOR _156_ (
    .A(y_1[6]),
    .B(_073_),
    .Y(_027_)
  );
  NOR _157_ (
    .A(data_in[6]),
    .B(_002_),
    .Y(_028_)
  );
  NOT _158_ (
    .A(_028_),
    .Y(_029_)
  );
  NAND _159_ (
    .A(reset),
    .B(_029_),
    .Y(_030_)
  );
  NOR _160_ (
    .A(_027_),
    .B(_030_),
    .Y(lane_1_c[6])
  );
  NOR _161_ (
    .A(y_1[7]),
    .B(_073_),
    .Y(_031_)
  );
  NOR _162_ (
    .A(data_in[7]),
    .B(_002_),
    .Y(_032_)
  );
  NOT _163_ (
    .A(_032_),
    .Y(_033_)
  );
  NAND _164_ (
    .A(reset),
    .B(_033_),
    .Y(_034_)
  );
  NOR _165_ (
    .A(_031_),
    .B(_034_),
    .Y(lane_1_c[7])
  );
  (* src = "./res/Byte_striping_estr.v:80" *)
  DFF _166_ (
    .C(clk_2f),
    .D(_000_),
    .Q(selector)
  );
  (* src = "./res/Byte_striping_estr.v:20" *)
  DFF _167_ (
    .C(clk_2f),
    .D(lane_0_c[0]),
    .Q(y_0[0])
  );
  (* src = "./res/Byte_striping_estr.v:20" *)
  DFF _168_ (
    .C(clk_2f),
    .D(lane_0_c[1]),
    .Q(y_0[1])
  );
  (* src = "./res/Byte_striping_estr.v:20" *)
  DFF _169_ (
    .C(clk_2f),
    .D(lane_0_c[2]),
    .Q(y_0[2])
  );
  (* src = "./res/Byte_striping_estr.v:20" *)
  DFF _170_ (
    .C(clk_2f),
    .D(lane_0_c[3]),
    .Q(y_0[3])
  );
  (* src = "./res/Byte_striping_estr.v:20" *)
  DFF _171_ (
    .C(clk_2f),
    .D(lane_0_c[4]),
    .Q(y_0[4])
  );
  (* src = "./res/Byte_striping_estr.v:20" *)
  DFF _172_ (
    .C(clk_2f),
    .D(lane_0_c[5]),
    .Q(y_0[5])
  );
  (* src = "./res/Byte_striping_estr.v:20" *)
  DFF _173_ (
    .C(clk_2f),
    .D(lane_0_c[6]),
    .Q(y_0[6])
  );
  (* src = "./res/Byte_striping_estr.v:20" *)
  DFF _174_ (
    .C(clk_2f),
    .D(lane_0_c[7]),
    .Q(y_0[7])
  );
  (* src = "./res/Byte_striping_estr.v:20" *)
  DFF _175_ (
    .C(clk_2f),
    .D(lane_1_c[0]),
    .Q(y_1[0])
  );
  (* src = "./res/Byte_striping_estr.v:20" *)
  DFF _176_ (
    .C(clk_2f),
    .D(lane_1_c[1]),
    .Q(y_1[1])
  );
  (* src = "./res/Byte_striping_estr.v:20" *)
  DFF _177_ (
    .C(clk_2f),
    .D(lane_1_c[2]),
    .Q(y_1[2])
  );
  (* src = "./res/Byte_striping_estr.v:20" *)
  DFF _178_ (
    .C(clk_2f),
    .D(lane_1_c[3]),
    .Q(y_1[3])
  );
  (* src = "./res/Byte_striping_estr.v:20" *)
  DFF _179_ (
    .C(clk_2f),
    .D(lane_1_c[4]),
    .Q(y_1[4])
  );
  (* src = "./res/Byte_striping_estr.v:20" *)
  DFF _180_ (
    .C(clk_2f),
    .D(lane_1_c[5]),
    .Q(y_1[5])
  );
  (* src = "./res/Byte_striping_estr.v:20" *)
  DFF _181_ (
    .C(clk_2f),
    .D(lane_1_c[6]),
    .Q(y_1[6])
  );
  (* src = "./res/Byte_striping_estr.v:20" *)
  DFF _182_ (
    .C(clk_2f),
    .D(lane_1_c[7]),
    .Q(y_1[7])
  );
  (* src = "./res/Byte_striping_estr.v:20" *)
  DFF _183_ (
    .C(clk_2f),
    .D(_001_),
    .Q(valid_atrasado)
  );
endmodule

(* src = "Byte_un_striping_estr.v:1" *)
module Byte_un_striping_estr(clk_f, clk_2f, lane_0, lane_1, valid_0, valid_1, reset, data_out_c, valid_out_c);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  (* src = "Byte_un_striping_estr.v:3" *)
  input clk_2f;
  (* src = "Byte_un_striping_estr.v:2" *)
  input clk_f;
  (* src = "Byte_un_striping_estr.v:9" *)
  output [7:0] data_out_c;
  (* onehot = 32'd1 *)
  wire [2:0] estado;
  (* src = "Byte_un_striping_estr.v:4" *)
  input [7:0] lane_0;
  (* src = "Byte_un_striping_estr.v:5" *)
  input [7:0] lane_1;
  (* src = "Byte_un_striping_estr.v:13" *)
  (* unused_bits = "0 1 2" *)
  wire [2:0] prox_estado;
  (* src = "Byte_un_striping_estr.v:8" *)
  input reset;
  (* src = "Byte_un_striping_estr.v:6" *)
  input valid_0;
  (* src = "Byte_un_striping_estr.v:7" *)
  input valid_1;
  (* src = "Byte_un_striping_estr.v:10" *)
  output valid_out_c;
  NOT _32_ (
    .A(valid_0),
    .Y(_03_)
  );
  NOT _33_ (
    .A(valid_1),
    .Y(_04_)
  );
  NOT _34_ (
    .A(estado[2]),
    .Y(_05_)
  );
  NOT _35_ (
    .A(reset),
    .Y(_06_)
  );
  NOR _36_ (
    .A(estado[1]),
    .B(estado[0]),
    .Y(_07_)
  );
  NOR _37_ (
    .A(valid_0),
    .B(_07_),
    .Y(_08_)
  );
  NAND _38_ (
    .A(_04_),
    .B(estado[2]),
    .Y(_09_)
  );
  NOR _39_ (
    .A(_06_),
    .B(_08_),
    .Y(_10_)
  );
  NAND _40_ (
    .A(_09_),
    .B(_10_),
    .Y(_02_)
  );
  NOR _41_ (
    .A(_04_),
    .B(_05_),
    .Y(_11_)
  );
  NAND _42_ (
    .A(lane_1[0]),
    .B(_11_),
    .Y(_12_)
  );
  NOR _43_ (
    .A(_03_),
    .B(_07_),
    .Y(_13_)
  );
  NAND _44_ (
    .A(lane_0[0]),
    .B(_13_),
    .Y(_14_)
  );
  NAND _45_ (
    .A(_12_),
    .B(_14_),
    .Y(data_out_c[0])
  );
  NAND _46_ (
    .A(lane_1[1]),
    .B(_11_),
    .Y(_15_)
  );
  NAND _47_ (
    .A(lane_0[1]),
    .B(_13_),
    .Y(_16_)
  );
  NAND _48_ (
    .A(_15_),
    .B(_16_),
    .Y(data_out_c[1])
  );
  NAND _49_ (
    .A(lane_1[2]),
    .B(_11_),
    .Y(_17_)
  );
  NAND _50_ (
    .A(lane_0[2]),
    .B(_13_),
    .Y(_18_)
  );
  NAND _51_ (
    .A(_17_),
    .B(_18_),
    .Y(data_out_c[2])
  );
  NAND _52_ (
    .A(lane_1[3]),
    .B(_11_),
    .Y(_19_)
  );
  NAND _53_ (
    .A(lane_0[3]),
    .B(_13_),
    .Y(_20_)
  );
  NAND _54_ (
    .A(_19_),
    .B(_20_),
    .Y(data_out_c[3])
  );
  NAND _55_ (
    .A(lane_1[4]),
    .B(_11_),
    .Y(_21_)
  );
  NAND _56_ (
    .A(lane_0[4]),
    .B(_13_),
    .Y(_22_)
  );
  NAND _57_ (
    .A(_21_),
    .B(_22_),
    .Y(data_out_c[4])
  );
  NAND _58_ (
    .A(lane_1[5]),
    .B(_11_),
    .Y(_23_)
  );
  NAND _59_ (
    .A(lane_0[5]),
    .B(_13_),
    .Y(_24_)
  );
  NAND _60_ (
    .A(_23_),
    .B(_24_),
    .Y(data_out_c[5])
  );
  NAND _61_ (
    .A(lane_1[6]),
    .B(_11_),
    .Y(_25_)
  );
  NAND _62_ (
    .A(lane_0[6]),
    .B(_13_),
    .Y(_26_)
  );
  NAND _63_ (
    .A(_25_),
    .B(_26_),
    .Y(data_out_c[6])
  );
  NAND _64_ (
    .A(lane_1[7]),
    .B(_11_),
    .Y(_27_)
  );
  NAND _65_ (
    .A(lane_0[7]),
    .B(_13_),
    .Y(_28_)
  );
  NAND _66_ (
    .A(_27_),
    .B(_28_),
    .Y(data_out_c[7])
  );
  NOR _67_ (
    .A(_11_),
    .B(_13_),
    .Y(_29_)
  );
  NOT _68_ (
    .A(_29_),
    .Y(valid_out_c)
  );
  NAND _69_ (
    .A(reset),
    .B(_13_),
    .Y(_30_)
  );
  NOT _70_ (
    .A(_30_),
    .Y(_01_)
  );
  NAND _71_ (
    .A(reset),
    .B(_11_),
    .Y(_31_)
  );
  NOT _72_ (
    .A(_31_),
    .Y(_00_)
  );
  DFF _73_ (
    .C(clk_2f),
    .D(_02_),
    .Q(estado[0])
  );
  DFF _74_ (
    .C(clk_2f),
    .D(_00_),
    .Q(estado[1])
  );
  DFF _75_ (
    .C(clk_2f),
    .D(_01_),
    .Q(estado[2])
  );
endmodule

(* src = "./res/Paralelo_Serie_estructural.v:2" *)
module Paralelo_Serie_estructural(clk_8f, clk_f, data_in, valid_in, reset, data2send_c, data_out_c);
  (* src = "./res/Paralelo_Serie_estructural.v:30" *)
  wire [2:0] _000_;
  (* src = "./res/Paralelo_Serie_estructural.v:39" *)
  wire [2:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  (* src = "./res/Paralelo_Serie_estructural.v:2" *)
  input clk_8f;
  (* src = "./res/Paralelo_Serie_estructural.v:3" *)
  input clk_f;
  (* src = "./res/Paralelo_Serie_estructural.v:7" *)
  output [7:0] data2send_c;
  (* src = "./res/Paralelo_Serie_estructural.v:4" *)
  input [7:0] data_in;
  (* src = "./res/Paralelo_Serie_estructural.v:8" *)
  output data_out_c;
  (* src = "./res/Paralelo_Serie_estructural.v:11" *)
  wire [2:0] j;
  (* src = "./res/Paralelo_Serie_estructural.v:11" *)
  wire [2:0] k;
  (* src = "./res/Paralelo_Serie_estructural.v:6" *)
  input reset;
  (* src = "./res/Paralelo_Serie_estructural.v:5" *)
  input valid_in;
  NOT _077_ (
    .A(data_in[1]),
    .Y(_023_)
  );
  NOT _078_ (
    .A(valid_in),
    .Y(_024_)
  );
  NOT _079_ (
    .A(data_in[2]),
    .Y(_025_)
  );
  NOT _080_ (
    .A(data_in[4]),
    .Y(_026_)
  );
  NOT _081_ (
    .A(data_in[5]),
    .Y(_027_)
  );
  NOT _082_ (
    .A(data_in[6]),
    .Y(_028_)
  );
  NOT _083_ (
    .A(reset),
    .Y(_029_)
  );
  NOT _084_ (
    .A(j[2]),
    .Y(_030_)
  );
  NOT _085_ (
    .A(j[0]),
    .Y(_031_)
  );
  NOT _086_ (
    .A(k[0]),
    .Y(_032_)
  );
  NOT _087_ (
    .A(k[2]),
    .Y(_033_)
  );
  NOR _088_ (
    .A(_023_),
    .B(_024_),
    .Y(data2send_c[1])
  );
  NAND _089_ (
    .A(valid_in),
    .B(_025_),
    .Y(data2send_c[2])
  );
  NOR _090_ (
    .A(_024_),
    .B(data_in[3]),
    .Y(_034_)
  );
  NOT _091_ (
    .A(_034_),
    .Y(data2send_c[3])
  );
  NAND _092_ (
    .A(valid_in),
    .B(_026_),
    .Y(data2send_c[4])
  );
  NAND _093_ (
    .A(valid_in),
    .B(_027_),
    .Y(data2send_c[5])
  );
  NOR _094_ (
    .A(_024_),
    .B(_028_),
    .Y(data2send_c[6])
  );
  NOR _095_ (
    .A(_024_),
    .B(data_in[7]),
    .Y(_035_)
  );
  NOT _096_ (
    .A(_035_),
    .Y(data2send_c[7])
  );
  NAND _097_ (
    .A(reset),
    .B(j[0]),
    .Y(_000_[0])
  );
  NOR _098_ (
    .A(j[1]),
    .B(j[0]),
    .Y(_036_)
  );
  NAND _099_ (
    .A(j[1]),
    .B(j[0]),
    .Y(_037_)
  );
  NOR _100_ (
    .A(_029_),
    .B(_036_),
    .Y(_038_)
  );
  NAND _101_ (
    .A(_037_),
    .B(_038_),
    .Y(_000_[1])
  );
  NOR _102_ (
    .A(j[2]),
    .B(_036_),
    .Y(_039_)
  );
  NOT _103_ (
    .A(_039_),
    .Y(_040_)
  );
  NAND _104_ (
    .A(j[2]),
    .B(_036_),
    .Y(_041_)
  );
  NAND _105_ (
    .A(_040_),
    .B(_041_),
    .Y(_042_)
  );
  NAND _106_ (
    .A(reset),
    .B(_042_),
    .Y(_000_[2])
  );
  NOR _107_ (
    .A(_024_),
    .B(_029_),
    .Y(_043_)
  );
  NAND _108_ (
    .A(valid_in),
    .B(reset),
    .Y(_044_)
  );
  NAND _109_ (
    .A(k[0]),
    .B(_043_),
    .Y(_001_[0])
  );
  NOR _110_ (
    .A(k[0]),
    .B(k[1]),
    .Y(_045_)
  );
  NAND _111_ (
    .A(k[0]),
    .B(k[1]),
    .Y(_046_)
  );
  NAND _112_ (
    .A(_043_),
    .B(_046_),
    .Y(_047_)
  );
  NOR _113_ (
    .A(_045_),
    .B(_047_),
    .Y(_048_)
  );
  NOT _114_ (
    .A(_048_),
    .Y(_001_[1])
  );
  NAND _115_ (
    .A(_033_),
    .B(_045_),
    .Y(_049_)
  );
  NOR _116_ (
    .A(_033_),
    .B(_045_),
    .Y(_050_)
  );
  NOR _117_ (
    .A(_044_),
    .B(_050_),
    .Y(_051_)
  );
  NAND _118_ (
    .A(_049_),
    .B(_051_),
    .Y(_001_[2])
  );
  NAND _119_ (
    .A(_031_),
    .B(data2send_c[4]),
    .Y(_052_)
  );
  NAND _120_ (
    .A(j[0]),
    .B(data2send_c[5]),
    .Y(_053_)
  );
  NAND _121_ (
    .A(_052_),
    .B(_053_),
    .Y(_054_)
  );
  NOR _122_ (
    .A(_030_),
    .B(_054_),
    .Y(_055_)
  );
  NAND _123_ (
    .A(valid_in),
    .B(data_in[0]),
    .Y(_056_)
  );
  NOT _124_ (
    .A(_056_),
    .Y(data2send_c[0])
  );
  NAND _125_ (
    .A(_031_),
    .B(data2send_c[0]),
    .Y(_057_)
  );
  NAND _126_ (
    .A(j[0]),
    .B(data2send_c[1]),
    .Y(_058_)
  );
  NAND _127_ (
    .A(_057_),
    .B(_058_),
    .Y(_059_)
  );
  NOR _128_ (
    .A(j[2]),
    .B(_059_),
    .Y(_060_)
  );
  NOR _129_ (
    .A(_031_),
    .B(_035_),
    .Y(_061_)
  );
  NAND _130_ (
    .A(_031_),
    .B(data2send_c[6]),
    .Y(_062_)
  );
  NOR _131_ (
    .A(_030_),
    .B(_061_),
    .Y(_063_)
  );
  NAND _132_ (
    .A(_062_),
    .B(_063_),
    .Y(_064_)
  );
  NAND _133_ (
    .A(_031_),
    .B(data2send_c[2]),
    .Y(_065_)
  );
  NOR _134_ (
    .A(_031_),
    .B(_034_),
    .Y(_066_)
  );
  NOR _135_ (
    .A(j[2]),
    .B(_066_),
    .Y(_067_)
  );
  NAND _136_ (
    .A(_065_),
    .B(_067_),
    .Y(_068_)
  );
  NOR _137_ (
    .A(_055_),
    .B(_060_),
    .Y(_069_)
  );
  NOR _138_ (
    .A(j[1]),
    .B(_069_),
    .Y(_070_)
  );
  NAND _139_ (
    .A(_064_),
    .B(_068_),
    .Y(_071_)
  );
  NAND _140_ (
    .A(j[1]),
    .B(_071_),
    .Y(_072_)
  );
  NAND _141_ (
    .A(_024_),
    .B(_072_),
    .Y(_073_)
  );
  NOR _142_ (
    .A(_070_),
    .B(_073_),
    .Y(_074_)
  );
  NAND _143_ (
    .A(k[0]),
    .B(_035_),
    .Y(_075_)
  );
  NOR _144_ (
    .A(k[0]),
    .B(data2send_c[6]),
    .Y(_076_)
  );
  NAND _145_ (
    .A(k[2]),
    .B(_075_),
    .Y(_002_)
  );
  NOR _146_ (
    .A(_076_),
    .B(_002_),
    .Y(_003_)
  );
  NOR _147_ (
    .A(k[0]),
    .B(data2send_c[2]),
    .Y(_004_)
  );
  NAND _148_ (
    .A(k[0]),
    .B(_034_),
    .Y(_005_)
  );
  NAND _149_ (
    .A(_033_),
    .B(_005_),
    .Y(_006_)
  );
  NOR _150_ (
    .A(_004_),
    .B(_006_),
    .Y(_007_)
  );
  NOR _151_ (
    .A(_003_),
    .B(_007_),
    .Y(_008_)
  );
  NAND _152_ (
    .A(_032_),
    .B(data2send_c[4]),
    .Y(_009_)
  );
  NAND _153_ (
    .A(k[0]),
    .B(data2send_c[5]),
    .Y(_010_)
  );
  NAND _154_ (
    .A(_009_),
    .B(_010_),
    .Y(_011_)
  );
  NAND _155_ (
    .A(k[2]),
    .B(_011_),
    .Y(_012_)
  );
  NOR _156_ (
    .A(k[0]),
    .B(data2send_c[0]),
    .Y(_013_)
  );
  NOR _157_ (
    .A(_032_),
    .B(data2send_c[1]),
    .Y(_014_)
  );
  NOR _158_ (
    .A(_013_),
    .B(_014_),
    .Y(_015_)
  );
  NAND _159_ (
    .A(_033_),
    .B(_015_),
    .Y(_016_)
  );
  NAND _160_ (
    .A(_012_),
    .B(_016_),
    .Y(_017_)
  );
  NAND _161_ (
    .A(k[1]),
    .B(_008_),
    .Y(_018_)
  );
  NOR _162_ (
    .A(k[1]),
    .B(_017_),
    .Y(_019_)
  );
  NAND _163_ (
    .A(valid_in),
    .B(_018_),
    .Y(_020_)
  );
  NOR _164_ (
    .A(_019_),
    .B(_020_),
    .Y(_021_)
  );
  NOR _165_ (
    .A(_074_),
    .B(_021_),
    .Y(_022_)
  );
  NOR _166_ (
    .A(_029_),
    .B(_022_),
    .Y(data_out_c)
  );
  (* src = "./res/Paralelo_Serie_estructural.v:39" *)
  DFF _167_ (
    .C(clk_8f),
    .D(_001_[0]),
    .Q(k[0])
  );
  (* src = "./res/Paralelo_Serie_estructural.v:39" *)
  DFF _168_ (
    .C(clk_8f),
    .D(_001_[1]),
    .Q(k[1])
  );
  (* src = "./res/Paralelo_Serie_estructural.v:39" *)
  DFF _169_ (
    .C(clk_8f),
    .D(_001_[2]),
    .Q(k[2])
  );
  (* src = "./res/Paralelo_Serie_estructural.v:30" *)
  DFF _170_ (
    .C(clk_8f),
    .D(_000_[0]),
    .Q(j[0])
  );
  (* src = "./res/Paralelo_Serie_estructural.v:30" *)
  DFF _171_ (
    .C(clk_8f),
    .D(_000_[1]),
    .Q(j[1])
  );
  (* src = "./res/Paralelo_Serie_estructural.v:30" *)
  DFF _172_ (
    .C(clk_8f),
    .D(_000_[2]),
    .Q(j[2])
  );
endmodule

(* src = "Serie_Paralelo_estructural.v:2" *)
module Serie_Paralelo_estructural(clk_8f, clk_f, data_in, reset, valid_out_c, parallel_out_c);
  (* src = "Serie_Paralelo_estructural.v:44" *)
  wire [2:0] _000_;
  (* src = "Serie_Paralelo_estructural.v:44" *)
  wire [7:0] _001_;
  (* src = "Serie_Paralelo_estructural.v:44" *)
  wire [2:0] _002_;
  (* src = "Serie_Paralelo_estructural.v:31" *)
  (* unused_bits = "0" *)
  wire [7:0] _003_;
  (* src = "Serie_Paralelo_estructural.v:31" *)
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  (* src = "Serie_Paralelo_estructural.v:12" *)
  wire [2:0] BC_counter;
  (* src = "Serie_Paralelo_estructural.v:11" *)
  wire [7:0] Data_P;
  (* src = "Serie_Paralelo_estructural.v:14" *)
  (* unused_bits = "0" *)
  wire active;
  (* src = "Serie_Paralelo_estructural.v:12" *)
  wire [2:0] bit_counter;
  (* src = "Serie_Paralelo_estructural.v:2" *)
  input clk_8f;
  (* src = "Serie_Paralelo_estructural.v:3" *)
  input clk_f;
  (* src = "Serie_Paralelo_estructural.v:4" *)
  input data_in;
  (* src = "Serie_Paralelo_estructural.v:61" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] i;
  (* src = "Serie_Paralelo_estructural.v:11" *)
  (* unused_bits = "0" *)
  wire [7:0] parallel_out_auxiliar;
  (* src = "Serie_Paralelo_estructural.v:7" *)
  output [7:0] parallel_out_c;
  (* src = "Serie_Paralelo_estructural.v:5" *)
  input reset;
  (* src = "Serie_Paralelo_estructural.v:6" *)
  output valid_out_c;
  (* src = "Serie_Paralelo_estructural.v:14" *)
  wire valid_out_c_retrasado;
  NOT _101_ (
    .A(Data_P[6]),
    .Y(_066_)
  );
  NOT _102_ (
    .A(bit_counter[2]),
    .Y(_067_)
  );
  NOT _103_ (
    .A(bit_counter[1]),
    .Y(_068_)
  );
  NOT _104_ (
    .A(bit_counter[0]),
    .Y(_069_)
  );
  NOT _105_ (
    .A(parallel_out_auxiliar[7]),
    .Y(_070_)
  );
  NOT _106_ (
    .A(reset),
    .Y(_071_)
  );
  NOT _107_ (
    .A(data_in),
    .Y(_072_)
  );
  NOT _108_ (
    .A(Data_P[7]),
    .Y(_073_)
  );
  NOT _109_ (
    .A(Data_P[5]),
    .Y(_074_)
  );
  NOT _110_ (
    .A(Data_P[4]),
    .Y(_075_)
  );
  NOT _111_ (
    .A(Data_P[3]),
    .Y(_076_)
  );
  NOT _112_ (
    .A(Data_P[2]),
    .Y(_077_)
  );
  NOT _113_ (
    .A(Data_P[1]),
    .Y(_078_)
  );
  NOT _114_ (
    .A(BC_counter[1]),
    .Y(_079_)
  );
  NOT _115_ (
    .A(BC_counter[2]),
    .Y(_080_)
  );
  NAND _116_ (
    .A(parallel_out_auxiliar[7]),
    .B(reset),
    .Y(_081_)
  );
  NOT _117_ (
    .A(_081_),
    .Y(parallel_out_c[7])
  );
  NAND _118_ (
    .A(parallel_out_auxiliar[4]),
    .B(parallel_out_auxiliar[2]),
    .Y(_082_)
  );
  NAND _119_ (
    .A(parallel_out_auxiliar[3]),
    .B(parallel_out_auxiliar[5]),
    .Y(_083_)
  );
  NOR _120_ (
    .A(_082_),
    .B(_083_),
    .Y(_084_)
  );
  NOT _121_ (
    .A(_084_),
    .Y(_085_)
  );
  NOR _122_ (
    .A(Data_P[0]),
    .B(parallel_out_auxiliar[1]),
    .Y(_086_)
  );
  NOR _123_ (
    .A(parallel_out_auxiliar[6]),
    .B(_070_),
    .Y(_087_)
  );
  NAND _124_ (
    .A(_086_),
    .B(_087_),
    .Y(_088_)
  );
  NOR _125_ (
    .A(_085_),
    .B(_088_),
    .Y(_089_)
  );
  NAND _126_ (
    .A(reset),
    .B(BC_counter[2]),
    .Y(_090_)
  );
  NOT _127_ (
    .A(_090_),
    .Y(_091_)
  );
  NAND _128_ (
    .A(valid_out_c_retrasado),
    .B(_091_),
    .Y(_092_)
  );
  NOR _129_ (
    .A(_089_),
    .B(_092_),
    .Y(valid_out_c)
  );
  NAND _130_ (
    .A(parallel_out_auxiliar[1]),
    .B(reset),
    .Y(_093_)
  );
  NOT _131_ (
    .A(_093_),
    .Y(parallel_out_c[1])
  );
  NAND _132_ (
    .A(Data_P[0]),
    .B(reset),
    .Y(_094_)
  );
  NOT _133_ (
    .A(_094_),
    .Y(parallel_out_c[0])
  );
  NAND _134_ (
    .A(reset),
    .B(parallel_out_auxiliar[4]),
    .Y(_095_)
  );
  NOT _135_ (
    .A(_095_),
    .Y(parallel_out_c[4])
  );
  NAND _136_ (
    .A(reset),
    .B(parallel_out_auxiliar[2]),
    .Y(_096_)
  );
  NOT _137_ (
    .A(_096_),
    .Y(parallel_out_c[2])
  );
  NAND _138_ (
    .A(reset),
    .B(parallel_out_auxiliar[3]),
    .Y(_097_)
  );
  NOT _139_ (
    .A(_097_),
    .Y(parallel_out_c[3])
  );
  NAND _140_ (
    .A(reset),
    .B(parallel_out_auxiliar[5]),
    .Y(_098_)
  );
  NOT _141_ (
    .A(_098_),
    .Y(parallel_out_c[5])
  );
  NAND _142_ (
    .A(parallel_out_auxiliar[6]),
    .B(reset),
    .Y(_099_)
  );
  NOT _143_ (
    .A(_099_),
    .Y(parallel_out_c[6])
  );
  NAND _144_ (
    .A(bit_counter[1]),
    .B(bit_counter[0]),
    .Y(_100_)
  );
  NOR _145_ (
    .A(_067_),
    .B(_100_),
    .Y(_005_)
  );
  NOR _146_ (
    .A(Data_P[7]),
    .B(_005_),
    .Y(_006_)
  );
  NAND _147_ (
    .A(_072_),
    .B(_005_),
    .Y(_007_)
  );
  NAND _148_ (
    .A(reset),
    .B(_007_),
    .Y(_008_)
  );
  NOR _149_ (
    .A(_006_),
    .B(_008_),
    .Y(_001_[7])
  );
  NOR _150_ (
    .A(_068_),
    .B(bit_counter[0]),
    .Y(_009_)
  );
  NAND _151_ (
    .A(bit_counter[2]),
    .B(_009_),
    .Y(_010_)
  );
  NAND _152_ (
    .A(_066_),
    .B(_010_),
    .Y(_011_)
  );
  NOR _153_ (
    .A(data_in),
    .B(_010_),
    .Y(_012_)
  );
  NAND _154_ (
    .A(reset),
    .B(_011_),
    .Y(_013_)
  );
  NOR _155_ (
    .A(_012_),
    .B(_013_),
    .Y(_001_[6])
  );
  NOR _156_ (
    .A(bit_counter[1]),
    .B(_069_),
    .Y(_014_)
  );
  NAND _157_ (
    .A(bit_counter[2]),
    .B(_014_),
    .Y(_015_)
  );
  NAND _158_ (
    .A(_074_),
    .B(_015_),
    .Y(_016_)
  );
  NOR _159_ (
    .A(data_in),
    .B(_015_),
    .Y(_017_)
  );
  NAND _160_ (
    .A(reset),
    .B(_016_),
    .Y(_018_)
  );
  NOR _161_ (
    .A(_017_),
    .B(_018_),
    .Y(_001_[5])
  );
  NOR _162_ (
    .A(bit_counter[1]),
    .B(bit_counter[0]),
    .Y(_019_)
  );
  NOT _163_ (
    .A(_019_),
    .Y(_020_)
  );
  NAND _164_ (
    .A(bit_counter[2]),
    .B(_019_),
    .Y(_021_)
  );
  NAND _165_ (
    .A(_075_),
    .B(_021_),
    .Y(_022_)
  );
  NOR _166_ (
    .A(data_in),
    .B(_021_),
    .Y(_023_)
  );
  NAND _167_ (
    .A(reset),
    .B(_022_),
    .Y(_024_)
  );
  NOR _168_ (
    .A(_023_),
    .B(_024_),
    .Y(_001_[4])
  );
  NOR _169_ (
    .A(bit_counter[2]),
    .B(_100_),
    .Y(_025_)
  );
  NOR _170_ (
    .A(Data_P[3]),
    .B(_025_),
    .Y(_026_)
  );
  NAND _171_ (
    .A(_072_),
    .B(_025_),
    .Y(_027_)
  );
  NAND _172_ (
    .A(reset),
    .B(_027_),
    .Y(_028_)
  );
  NOR _173_ (
    .A(_026_),
    .B(_028_),
    .Y(_001_[3])
  );
  NAND _174_ (
    .A(_067_),
    .B(_009_),
    .Y(_029_)
  );
  NAND _175_ (
    .A(_077_),
    .B(_029_),
    .Y(_030_)
  );
  NOR _176_ (
    .A(data_in),
    .B(_029_),
    .Y(_031_)
  );
  NAND _177_ (
    .A(reset),
    .B(_030_),
    .Y(_032_)
  );
  NOR _178_ (
    .A(_031_),
    .B(_032_),
    .Y(_001_[2])
  );
  NAND _179_ (
    .A(_067_),
    .B(_014_),
    .Y(_033_)
  );
  NAND _180_ (
    .A(_078_),
    .B(_033_),
    .Y(_034_)
  );
  NOR _181_ (
    .A(data_in),
    .B(_033_),
    .Y(_035_)
  );
  NAND _182_ (
    .A(reset),
    .B(_034_),
    .Y(_036_)
  );
  NOR _183_ (
    .A(_035_),
    .B(_036_),
    .Y(_001_[1])
  );
  NOR _184_ (
    .A(bit_counter[2]),
    .B(_020_),
    .Y(_037_)
  );
  NAND _185_ (
    .A(_072_),
    .B(_037_),
    .Y(_038_)
  );
  NAND _186_ (
    .A(reset),
    .B(_038_),
    .Y(_039_)
  );
  NOR _187_ (
    .A(Data_P[0]),
    .B(_037_),
    .Y(_040_)
  );
  NOR _188_ (
    .A(_039_),
    .B(_040_),
    .Y(_001_[0])
  );
  NAND _189_ (
    .A(Data_P[4]),
    .B(Data_P[3]),
    .Y(_041_)
  );
  NAND _190_ (
    .A(Data_P[2]),
    .B(_078_),
    .Y(_042_)
  );
  NOR _191_ (
    .A(_041_),
    .B(_042_),
    .Y(_043_)
  );
  NOR _192_ (
    .A(Data_P[6]),
    .B(Data_P[0]),
    .Y(_044_)
  );
  NOT _193_ (
    .A(_044_),
    .Y(_045_)
  );
  NAND _194_ (
    .A(Data_P[7]),
    .B(Data_P[5]),
    .Y(_046_)
  );
  NOR _195_ (
    .A(_045_),
    .B(_046_),
    .Y(_047_)
  );
  NAND _196_ (
    .A(_043_),
    .B(_047_),
    .Y(_048_)
  );
  NAND _197_ (
    .A(_080_),
    .B(_037_),
    .Y(_049_)
  );
  NOR _198_ (
    .A(_048_),
    .B(_049_),
    .Y(_050_)
  );
  NOR _199_ (
    .A(BC_counter[0]),
    .B(_050_),
    .Y(_051_)
  );
  NOT _200_ (
    .A(_051_),
    .Y(_052_)
  );
  NAND _201_ (
    .A(reset),
    .B(_052_),
    .Y(_053_)
  );
  NAND _202_ (
    .A(BC_counter[0]),
    .B(_050_),
    .Y(_054_)
  );
  NOT _203_ (
    .A(_054_),
    .Y(_055_)
  );
  NOR _204_ (
    .A(_053_),
    .B(_055_),
    .Y(_000_[0])
  );
  NAND _205_ (
    .A(_079_),
    .B(_054_),
    .Y(_056_)
  );
  NAND _206_ (
    .A(reset),
    .B(_056_),
    .Y(_057_)
  );
  NOR _207_ (
    .A(_079_),
    .B(_054_),
    .Y(_058_)
  );
  NOR _208_ (
    .A(_057_),
    .B(_058_),
    .Y(_000_[1])
  );
  NOR _209_ (
    .A(BC_counter[2]),
    .B(_058_),
    .Y(_059_)
  );
  NOR _210_ (
    .A(_071_),
    .B(_059_),
    .Y(_000_[2])
  );
  NAND _211_ (
    .A(BC_counter[2]),
    .B(_048_),
    .Y(_060_)
  );
  NOT _212_ (
    .A(_060_),
    .Y(_004_)
  );
  NAND _213_ (
    .A(Data_P[1]),
    .B(BC_counter[2]),
    .Y(_061_)
  );
  NOT _214_ (
    .A(_061_),
    .Y(_003_[1])
  );
  NOR _215_ (
    .A(_077_),
    .B(_060_),
    .Y(_003_[2])
  );
  NOR _216_ (
    .A(_076_),
    .B(_060_),
    .Y(_003_[3])
  );
  NOR _217_ (
    .A(_075_),
    .B(_060_),
    .Y(_003_[4])
  );
  NOR _218_ (
    .A(_074_),
    .B(_060_),
    .Y(_003_[5])
  );
  NAND _219_ (
    .A(Data_P[6]),
    .B(BC_counter[2]),
    .Y(_062_)
  );
  NOT _220_ (
    .A(_062_),
    .Y(_003_[6])
  );
  NOR _221_ (
    .A(_073_),
    .B(_060_),
    .Y(_003_[7])
  );
  NAND _222_ (
    .A(bit_counter[0]),
    .B(reset),
    .Y(_002_[0])
  );
  NOR _223_ (
    .A(_071_),
    .B(_019_),
    .Y(_063_)
  );
  NAND _224_ (
    .A(_100_),
    .B(_063_),
    .Y(_002_[1])
  );
  NAND _225_ (
    .A(bit_counter[2]),
    .B(_020_),
    .Y(_064_)
  );
  NOR _226_ (
    .A(_071_),
    .B(_037_),
    .Y(_065_)
  );
  NAND _227_ (
    .A(_064_),
    .B(_065_),
    .Y(_002_[2])
  );
  (* src = "Serie_Paralelo_estructural.v:44" *)
  DFF _228_ (
    .C(clk_8f),
    .D(_002_[0]),
    .Q(bit_counter[0])
  );
  (* src = "Serie_Paralelo_estructural.v:44" *)
  DFF _229_ (
    .C(clk_8f),
    .D(_002_[1]),
    .Q(bit_counter[1])
  );
  (* src = "Serie_Paralelo_estructural.v:44" *)
  DFF _230_ (
    .C(clk_8f),
    .D(_002_[2]),
    .Q(bit_counter[2])
  );
  (* src = "Serie_Paralelo_estructural.v:44" *)
  DFF _231_ (
    .C(clk_8f),
    .D(_000_[0]),
    .Q(BC_counter[0])
  );
  (* src = "Serie_Paralelo_estructural.v:44" *)
  DFF _232_ (
    .C(clk_8f),
    .D(_000_[1]),
    .Q(BC_counter[1])
  );
  (* src = "Serie_Paralelo_estructural.v:44" *)
  DFF _233_ (
    .C(clk_8f),
    .D(_000_[2]),
    .Q(BC_counter[2])
  );
  (* src = "Serie_Paralelo_estructural.v:44" *)
  DFF _234_ (
    .C(clk_8f),
    .D(_001_[0]),
    .Q(Data_P[0])
  );
  (* src = "Serie_Paralelo_estructural.v:44" *)
  DFF _235_ (
    .C(clk_8f),
    .D(_001_[1]),
    .Q(Data_P[1])
  );
  (* src = "Serie_Paralelo_estructural.v:44" *)
  DFF _236_ (
    .C(clk_8f),
    .D(_001_[2]),
    .Q(Data_P[2])
  );
  (* src = "Serie_Paralelo_estructural.v:44" *)
  DFF _237_ (
    .C(clk_8f),
    .D(_001_[3]),
    .Q(Data_P[3])
  );
  (* src = "Serie_Paralelo_estructural.v:44" *)
  DFF _238_ (
    .C(clk_8f),
    .D(_001_[4]),
    .Q(Data_P[4])
  );
  (* src = "Serie_Paralelo_estructural.v:44" *)
  DFF _239_ (
    .C(clk_8f),
    .D(_001_[5]),
    .Q(Data_P[5])
  );
  (* src = "Serie_Paralelo_estructural.v:44" *)
  DFF _240_ (
    .C(clk_8f),
    .D(_001_[6]),
    .Q(Data_P[6])
  );
  (* src = "Serie_Paralelo_estructural.v:44" *)
  DFF _241_ (
    .C(clk_8f),
    .D(_001_[7]),
    .Q(Data_P[7])
  );
  (* src = "Serie_Paralelo_estructural.v:31" *)
  DFF _242_ (
    .C(clk_f),
    .D(_003_[1]),
    .Q(parallel_out_auxiliar[1])
  );
  (* src = "Serie_Paralelo_estructural.v:31" *)
  DFF _243_ (
    .C(clk_f),
    .D(_003_[2]),
    .Q(parallel_out_auxiliar[2])
  );
  (* src = "Serie_Paralelo_estructural.v:31" *)
  DFF _244_ (
    .C(clk_f),
    .D(_003_[3]),
    .Q(parallel_out_auxiliar[3])
  );
  (* src = "Serie_Paralelo_estructural.v:31" *)
  DFF _245_ (
    .C(clk_f),
    .D(_003_[4]),
    .Q(parallel_out_auxiliar[4])
  );
  (* src = "Serie_Paralelo_estructural.v:31" *)
  DFF _246_ (
    .C(clk_f),
    .D(_003_[5]),
    .Q(parallel_out_auxiliar[5])
  );
  (* src = "Serie_Paralelo_estructural.v:31" *)
  DFF _247_ (
    .C(clk_f),
    .D(_003_[6]),
    .Q(parallel_out_auxiliar[6])
  );
  (* src = "Serie_Paralelo_estructural.v:31" *)
  DFF _248_ (
    .C(clk_f),
    .D(_003_[7]),
    .Q(parallel_out_auxiliar[7])
  );
  (* src = "Serie_Paralelo_estructural.v:31" *)
  DFF _249_ (
    .C(clk_f),
    .D(_004_),
    .Q(valid_out_c_retrasado)
  );
endmodule

(* src = "clkgen_estr.v:1" *)
module clkgen_estr(clk_f, clk_2f, clk_8f, clk_8f_in, resetCLK);
  (* src = "clkgen_estr.v:11" *)
  wire _00_;
  (* src = "clkgen_estr.v:11" *)
  wire _01_;
  (* src = "clkgen_estr.v:11" *)
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  (* src = "clkgen_estr.v:3" *)
  output clk_2f;
  (* src = "clkgen_estr.v:8" *)
  wire clk_4f;
  (* src = "clkgen_estr.v:4" *)
  output clk_8f;
  (* src = "clkgen_estr.v:5" *)
  input clk_8f_in;
  (* src = "clkgen_estr.v:2" *)
  output clk_f;
  (* src = "clkgen_estr.v:6" *)
  input resetCLK;
  NOT _13_ (
    .A(resetCLK),
    .Y(_11_)
  );
  NOR _14_ (
    .A(clk_4f),
    .B(clk_2f),
    .Y(_12_)
  );
  NAND _15_ (
    .A(clk_f),
    .B(_12_),
    .Y(_03_)
  );
  NOT _16_ (
    .A(_03_),
    .Y(_04_)
  );
  NOR _17_ (
    .A(clk_f),
    .B(_12_),
    .Y(_05_)
  );
  NOT _18_ (
    .A(_05_),
    .Y(_06_)
  );
  NAND _19_ (
    .A(resetCLK),
    .B(_06_),
    .Y(_07_)
  );
  NOR _20_ (
    .A(_04_),
    .B(_07_),
    .Y(_02_)
  );
  NAND _21_ (
    .A(clk_4f),
    .B(clk_2f),
    .Y(_08_)
  );
  NOT _22_ (
    .A(_08_),
    .Y(_09_)
  );
  NOR _23_ (
    .A(_12_),
    .B(_09_),
    .Y(_10_)
  );
  NOR _24_ (
    .A(_11_),
    .B(_10_),
    .Y(_00_)
  );
  NOR _25_ (
    .A(_11_),
    .B(clk_4f),
    .Y(_01_)
  );
  (* src = "clkgen_estr.v:11" *)
  DFF _26_ (
    .C(clk_8f_in),
    .D(_02_),
    .Q(clk_f)
  );
  (* src = "clkgen_estr.v:11" *)
  DFF _27_ (
    .C(clk_8f_in),
    .D(_00_),
    .Q(clk_2f)
  );
  (* src = "clkgen_estr.v:11" *)
  DFF _28_ (
    .C(clk_8f_in),
    .D(_01_),
    .Q(clk_4f)
  );
  assign clk_8f = clk_8f_in;
endmodule

(* src = "demux_estr_estr.v:1" *)
module demux_estr_estr(data_out_0_c, valid_out_0_c, data_out_1_c, valid_out_1_c, data_in_c, valid_in_c, reset, clk2f, clk8f);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  (* src = "demux_estr_estr.v:9" *)
  input clk2f;
  (* src = "demux_estr_estr.v:10" *)
  input clk8f;
  (* src = "demux_estr_estr.v:6" *)
  input [7:0] data_in_c;
  (* src = "demux_estr_estr.v:2" *)
  output [7:0] data_out_0_c;
  (* src = "demux_estr_estr.v:4" *)
  output [7:0] data_out_1_c;
  (* src = "demux_estr_estr.v:12" *)
  (* unused_bits = "0 1 2 3 4 5" *)
  wire [5:0] nxt_st;
  (* src = "demux_estr_estr.v:8" *)
  input reset;
  (* src = "demux_estr_estr.v:13" *)
  wire reset2;
  (* src = "demux_estr_estr.v:13" *)
  wire resetm;
  (* onehot = 32'd1 *)
  wire [5:0] st;
  (* src = "demux_estr_estr.v:7" *)
  input valid_in_c;
  (* src = "demux_estr_estr.v:3" *)
  output valid_out_0_c;
  (* src = "demux_estr_estr.v:5" *)
  output valid_out_1_c;
  NOT _32_ (
    .A(st[5]),
    .Y(_06_)
  );
  NOT _33_ (
    .A(valid_in_c),
    .Y(_07_)
  );
  NOT _34_ (
    .A(data_in_c[0]),
    .Y(_08_)
  );
  NOT _35_ (
    .A(data_in_c[1]),
    .Y(_09_)
  );
  NOT _36_ (
    .A(data_in_c[2]),
    .Y(_10_)
  );
  NOT _37_ (
    .A(data_in_c[3]),
    .Y(_11_)
  );
  NOT _38_ (
    .A(data_in_c[4]),
    .Y(_12_)
  );
  NOT _39_ (
    .A(data_in_c[5]),
    .Y(_13_)
  );
  NOT _40_ (
    .A(data_in_c[6]),
    .Y(_14_)
  );
  NOT _41_ (
    .A(data_in_c[7]),
    .Y(_15_)
  );
  NOT _42_ (
    .A(reset2),
    .Y(_16_)
  );
  NAND _43_ (
    .A(reset),
    .B(reset2),
    .Y(_17_)
  );
  NOT _44_ (
    .A(_17_),
    .Y(_18_)
  );
  NOR _45_ (
    .A(_16_),
    .B(st[0]),
    .Y(_19_)
  );
  NOR _46_ (
    .A(_18_),
    .B(_19_),
    .Y(_04_)
  );
  NOR _47_ (
    .A(valid_in_c),
    .B(_16_),
    .Y(_20_)
  );
  NAND _48_ (
    .A(_07_),
    .B(reset2),
    .Y(_21_)
  );
  NAND _49_ (
    .A(st[5]),
    .B(_20_),
    .Y(_22_)
  );
  NAND _50_ (
    .A(st[0]),
    .B(_18_),
    .Y(_23_)
  );
  NAND _51_ (
    .A(_22_),
    .B(_23_),
    .Y(_05_)
  );
  NOR _52_ (
    .A(st[3]),
    .B(st[1]),
    .Y(_24_)
  );
  NOT _53_ (
    .A(_24_),
    .Y(_25_)
  );
  NAND _54_ (
    .A(valid_in_c),
    .B(_25_),
    .Y(_26_)
  );
  NOT _55_ (
    .A(_26_),
    .Y(valid_out_1_c)
  );
  NOR _56_ (
    .A(_08_),
    .B(_26_),
    .Y(data_out_1_c[0])
  );
  NOR _57_ (
    .A(_09_),
    .B(_26_),
    .Y(data_out_1_c[1])
  );
  NOR _58_ (
    .A(_10_),
    .B(_26_),
    .Y(data_out_1_c[2])
  );
  NOR _59_ (
    .A(_11_),
    .B(_26_),
    .Y(data_out_1_c[3])
  );
  NOR _60_ (
    .A(_12_),
    .B(_26_),
    .Y(data_out_1_c[4])
  );
  NOR _61_ (
    .A(_13_),
    .B(_26_),
    .Y(data_out_1_c[5])
  );
  NOR _62_ (
    .A(_14_),
    .B(_26_),
    .Y(data_out_1_c[6])
  );
  NOR _63_ (
    .A(_15_),
    .B(_26_),
    .Y(data_out_1_c[7])
  );
  NOR _64_ (
    .A(st[2]),
    .B(st[4]),
    .Y(_27_)
  );
  NAND _65_ (
    .A(_06_),
    .B(_27_),
    .Y(_28_)
  );
  NAND _66_ (
    .A(valid_in_c),
    .B(_28_),
    .Y(_29_)
  );
  NOT _67_ (
    .A(_29_),
    .Y(valid_out_0_c)
  );
  NOR _68_ (
    .A(_08_),
    .B(_29_),
    .Y(data_out_0_c[0])
  );
  NOR _69_ (
    .A(_09_),
    .B(_29_),
    .Y(data_out_0_c[1])
  );
  NOR _70_ (
    .A(_10_),
    .B(_29_),
    .Y(data_out_0_c[2])
  );
  NOR _71_ (
    .A(_11_),
    .B(_29_),
    .Y(data_out_0_c[3])
  );
  NOR _72_ (
    .A(_12_),
    .B(_29_),
    .Y(data_out_0_c[4])
  );
  NOR _73_ (
    .A(_13_),
    .B(_29_),
    .Y(data_out_0_c[5])
  );
  NOR _74_ (
    .A(_14_),
    .B(_29_),
    .Y(data_out_0_c[6])
  );
  NOR _75_ (
    .A(_15_),
    .B(_29_),
    .Y(data_out_0_c[7])
  );
  NOR _76_ (
    .A(_16_),
    .B(_29_),
    .Y(_03_)
  );
  NOR _77_ (
    .A(st[3]),
    .B(st[2]),
    .Y(_30_)
  );
  NOR _78_ (
    .A(_21_),
    .B(_30_),
    .Y(_01_)
  );
  NOR _79_ (
    .A(st[1]),
    .B(st[4]),
    .Y(_31_)
  );
  NOR _80_ (
    .A(_21_),
    .B(_31_),
    .Y(_00_)
  );
  NOR _81_ (
    .A(_16_),
    .B(_26_),
    .Y(_02_)
  );
  DFF _82_ (
    .C(clk2f),
    .D(_04_),
    .Q(st[0])
  );
  DFF _83_ (
    .C(clk2f),
    .D(_00_),
    .Q(st[1])
  );
  DFF _84_ (
    .C(clk2f),
    .D(_01_),
    .Q(st[2])
  );
  DFF _85_ (
    .C(clk2f),
    .D(_02_),
    .Q(st[3])
  );
  DFF _86_ (
    .C(clk2f),
    .D(_03_),
    .Q(st[4])
  );
  DFF _87_ (
    .C(clk2f),
    .D(_05_),
    .Q(st[5])
  );
  (* src = "demux_estr_estr.v:23" *)
  DFF _88_ (
    .C(clk8f),
    .D(resetm),
    .Q(reset2)
  );
  (* src = "demux_estr_estr.v:23" *)
  DFF _89_ (
    .C(clk8f),
    .D(reset),
    .Q(resetm)
  );
endmodule

(* src = "./res/mux_estr.v:1" *)
module mux_estr(data_out_c, valid_out_c, data_in_0_c, valid_in_0_c, data_in_1_c, valid_in_1_c, reset, clk_2f, clk_8f);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  (* src = "./res/mux_estr.v:9" *)
  input clk_2f;
  (* src = "./res/mux_estr.v:10" *)
  input clk_8f;
  (* src = "./res/mux_estr.v:4" *)
  input [7:0] data_in_0_c;
  (* src = "./res/mux_estr.v:6" *)
  input [7:0] data_in_1_c;
  (* src = "./res/mux_estr.v:2" *)
  output [7:0] data_out_c;
  (* src = "./res/mux_estr.v:12" *)
  (* unused_bits = "0 1 2 3 4 5" *)
  wire [5:0] nxt_st;
  (* src = "./res/mux_estr.v:8" *)
  input reset;
  (* src = "./res/mux_estr.v:13" *)
  wire reset2;
  (* src = "./res/mux_estr.v:13" *)
  wire resetm;
  (* onehot = 32'd1 *)
  wire [5:0] st;
  (* src = "./res/mux_estr.v:5" *)
  input valid_in_0_c;
  (* src = "./res/mux_estr.v:7" *)
  input valid_in_1_c;
  (* src = "./res/mux_estr.v:3" *)
  output valid_out_c;
  NOT _071_ (
    .A(reset),
    .Y(_020_)
  );
  NOT _072_ (
    .A(st[5]),
    .Y(_021_)
  );
  NOT _073_ (
    .A(st[2]),
    .Y(_022_)
  );
  NOT _074_ (
    .A(valid_in_0_c),
    .Y(_023_)
  );
  NOT _075_ (
    .A(valid_in_1_c),
    .Y(_024_)
  );
  NOT _076_ (
    .A(reset2),
    .Y(_025_)
  );
  NOR _077_ (
    .A(valid_in_0_c),
    .B(valid_in_1_c),
    .Y(_026_)
  );
  NAND _078_ (
    .A(reset2),
    .B(_026_),
    .Y(_027_)
  );
  NOT _079_ (
    .A(_027_),
    .Y(_028_)
  );
  NAND _080_ (
    .A(st[5]),
    .B(_028_),
    .Y(_029_)
  );
  NAND _081_ (
    .A(reset),
    .B(reset2),
    .Y(_030_)
  );
  NOT _082_ (
    .A(_030_),
    .Y(_031_)
  );
  NAND _083_ (
    .A(st[0]),
    .B(_031_),
    .Y(_032_)
  );
  NAND _084_ (
    .A(_029_),
    .B(_032_),
    .Y(_005_)
  );
  NOR _085_ (
    .A(_025_),
    .B(_026_),
    .Y(_033_)
  );
  NAND _086_ (
    .A(st[4]),
    .B(_033_),
    .Y(_034_)
  );
  NAND _087_ (
    .A(valid_in_0_c),
    .B(reset2),
    .Y(_035_)
  );
  NOR _088_ (
    .A(st[5]),
    .B(st[2]),
    .Y(_036_)
  );
  NAND _089_ (
    .A(_021_),
    .B(_022_),
    .Y(_037_)
  );
  NAND _090_ (
    .A(valid_in_1_c),
    .B(_037_),
    .Y(_038_)
  );
  NOR _091_ (
    .A(_035_),
    .B(_038_),
    .Y(_039_)
  );
  NOR _092_ (
    .A(st[1]),
    .B(_037_),
    .Y(_040_)
  );
  NOR _093_ (
    .A(_023_),
    .B(valid_in_1_c),
    .Y(_041_)
  );
  NAND _094_ (
    .A(reset2),
    .B(_041_),
    .Y(_042_)
  );
  NOR _095_ (
    .A(_040_),
    .B(_042_),
    .Y(_043_)
  );
  NOR _096_ (
    .A(_039_),
    .B(_043_),
    .Y(_044_)
  );
  NAND _097_ (
    .A(_034_),
    .B(_044_),
    .Y(_004_)
  );
  NOR _098_ (
    .A(st[1]),
    .B(st[4]),
    .Y(_045_)
  );
  NOR _099_ (
    .A(_027_),
    .B(_045_),
    .Y(_001_)
  );
  NOR _100_ (
    .A(valid_in_0_c),
    .B(_024_),
    .Y(_046_)
  );
  NAND _101_ (
    .A(reset2),
    .B(_046_),
    .Y(_047_)
  );
  NOR _102_ (
    .A(_040_),
    .B(_047_),
    .Y(_048_)
  );
  NAND _103_ (
    .A(st[3]),
    .B(_033_),
    .Y(_049_)
  );
  NAND _104_ (
    .A(st[1]),
    .B(valid_in_1_c),
    .Y(_050_)
  );
  NOR _105_ (
    .A(_035_),
    .B(_050_),
    .Y(_051_)
  );
  NOR _106_ (
    .A(_048_),
    .B(_051_),
    .Y(_052_)
  );
  NAND _107_ (
    .A(_049_),
    .B(_052_),
    .Y(_003_)
  );
  NOR _108_ (
    .A(st[2]),
    .B(st[3]),
    .Y(_053_)
  );
  NOR _109_ (
    .A(_027_),
    .B(_053_),
    .Y(_002_)
  );
  NAND _110_ (
    .A(st[3]),
    .B(valid_in_1_c),
    .Y(_054_)
  );
  NOT _111_ (
    .A(_054_),
    .Y(_055_)
  );
  NAND _112_ (
    .A(st[4]),
    .B(valid_in_0_c),
    .Y(_056_)
  );
  NOT _113_ (
    .A(_056_),
    .Y(_057_)
  );
  NAND _114_ (
    .A(_040_),
    .B(_056_),
    .Y(_058_)
  );
  NOR _115_ (
    .A(_055_),
    .B(_058_),
    .Y(_059_)
  );
  NOR _116_ (
    .A(_026_),
    .B(_059_),
    .Y(valid_out_c)
  );
  NAND _117_ (
    .A(_050_),
    .B(_054_),
    .Y(_060_)
  );
  NOT _118_ (
    .A(_060_),
    .Y(_061_)
  );
  NAND _119_ (
    .A(_037_),
    .B(_046_),
    .Y(_062_)
  );
  NAND _120_ (
    .A(_061_),
    .B(_062_),
    .Y(_063_)
  );
  NAND _121_ (
    .A(data_in_1_c[0]),
    .B(_063_),
    .Y(_064_)
  );
  NAND _122_ (
    .A(st[1]),
    .B(_041_),
    .Y(_065_)
  );
  NOR _123_ (
    .A(_023_),
    .B(_036_),
    .Y(_066_)
  );
  NOR _124_ (
    .A(_057_),
    .B(_066_),
    .Y(_067_)
  );
  NAND _125_ (
    .A(_065_),
    .B(_067_),
    .Y(_068_)
  );
  NAND _126_ (
    .A(data_in_0_c[0]),
    .B(_068_),
    .Y(_069_)
  );
  NAND _127_ (
    .A(_064_),
    .B(_069_),
    .Y(data_out_c[0])
  );
  NAND _128_ (
    .A(data_in_1_c[1]),
    .B(_063_),
    .Y(_070_)
  );
  NAND _129_ (
    .A(data_in_0_c[1]),
    .B(_068_),
    .Y(_006_)
  );
  NAND _130_ (
    .A(_070_),
    .B(_006_),
    .Y(data_out_c[1])
  );
  NAND _131_ (
    .A(data_in_0_c[2]),
    .B(_068_),
    .Y(_007_)
  );
  NAND _132_ (
    .A(data_in_1_c[2]),
    .B(_063_),
    .Y(_008_)
  );
  NAND _133_ (
    .A(_007_),
    .B(_008_),
    .Y(data_out_c[2])
  );
  NAND _134_ (
    .A(data_in_1_c[3]),
    .B(_063_),
    .Y(_009_)
  );
  NAND _135_ (
    .A(data_in_0_c[3]),
    .B(_068_),
    .Y(_010_)
  );
  NAND _136_ (
    .A(_009_),
    .B(_010_),
    .Y(data_out_c[3])
  );
  NAND _137_ (
    .A(data_in_1_c[4]),
    .B(_063_),
    .Y(_011_)
  );
  NAND _138_ (
    .A(data_in_0_c[4]),
    .B(_068_),
    .Y(_012_)
  );
  NAND _139_ (
    .A(_011_),
    .B(_012_),
    .Y(data_out_c[4])
  );
  NAND _140_ (
    .A(data_in_0_c[5]),
    .B(_068_),
    .Y(_013_)
  );
  NAND _141_ (
    .A(data_in_1_c[5]),
    .B(_063_),
    .Y(_014_)
  );
  NAND _142_ (
    .A(_013_),
    .B(_014_),
    .Y(data_out_c[5])
  );
  NAND _143_ (
    .A(data_in_0_c[6]),
    .B(_068_),
    .Y(_015_)
  );
  NAND _144_ (
    .A(data_in_1_c[6]),
    .B(_063_),
    .Y(_016_)
  );
  NAND _145_ (
    .A(_015_),
    .B(_016_),
    .Y(data_out_c[6])
  );
  NAND _146_ (
    .A(data_in_1_c[7]),
    .B(_063_),
    .Y(_017_)
  );
  NAND _147_ (
    .A(data_in_0_c[7]),
    .B(_068_),
    .Y(_018_)
  );
  NAND _148_ (
    .A(_017_),
    .B(_018_),
    .Y(data_out_c[7])
  );
  NAND _149_ (
    .A(_020_),
    .B(st[0]),
    .Y(_019_)
  );
  NAND _150_ (
    .A(reset2),
    .B(_019_),
    .Y(_000_)
  );
  DFF _151_ (
    .C(clk_2f),
    .D(_000_),
    .Q(st[0])
  );
  DFF _152_ (
    .C(clk_2f),
    .D(_001_),
    .Q(st[1])
  );
  DFF _153_ (
    .C(clk_2f),
    .D(_002_),
    .Q(st[2])
  );
  DFF _154_ (
    .C(clk_2f),
    .D(_003_),
    .Q(st[3])
  );
  DFF _155_ (
    .C(clk_2f),
    .D(_004_),
    .Q(st[4])
  );
  DFF _156_ (
    .C(clk_2f),
    .D(_005_),
    .Q(st[5])
  );
  (* src = "./res/mux_estr.v:24" *)
  DFF _157_ (
    .C(clk_8f),
    .D(resetm),
    .Q(reset2)
  );
  (* src = "./res/mux_estr.v:24" *)
  DFF _158_ (
    .C(clk_8f),
    .D(reset),
    .Q(resetm)
  );
endmodule

(* top =  1  *)
(* src = "phy_cond.v:5" *)
module phy_estr(data_in_0_c, data_in_1_c, valid_in_0_c, valid_in_1_c, clk_8f_probador, resetCLK, reset, clk_2f_to_prob_estr, data_out_e_0, data_out_e_1, valid_out_e_0, valid_out_e_1);
  (* src = "phy_cond.v:20" *)
  wire Paral_serial_out_0_c;
  (* src = "phy_cond.v:21" *)
  wire Paral_serial_out_1_c;
  (* src = "phy_cond.v:22" *)
  wire clk_2f;
  (* src = "phy_cond.v:13" *)
  output clk_2f_to_prob_estr;
  (* src = "phy_cond.v:36" *)
  wire clk_8f;
  (* src = "phy_cond.v:10" *)
  input clk_8f_probador;
  (* src = "phy_cond.v:24" *)
  wire clk_f;
  (* src = "phy_cond.v:23" *)
  wire clk_f_negado;
  (* src = "phy_cond.v:6" *)
  input [7:0] data_in_0_c;
  (* src = "phy_cond.v:7" *)
  input [7:0] data_in_1_c;
  (* src = "phy_cond.v:14" *)
  output [7:0] data_out_e_0;
  (* src = "phy_cond.v:15" *)
  output [7:0] data_out_e_1;
  (* src = "phy_cond.v:12" *)
  input reset;
  (* src = "phy_cond.v:11" *)
  input resetCLK;
  (* src = "phy_cond.v:8" *)
  input valid_in_0_c;
  (* src = "phy_cond.v:9" *)
  input valid_in_1_c;
  (* src = "phy_cond.v:16" *)
  output valid_out_e_0;
  (* src = "phy_cond.v:17" *)
  output valid_out_e_1;
  NOT _0_ (
    .A(clk_f),
    .Y(clk_f_negado)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_cond.v:55" *)
  clkgen_estr clkgen_estr_cond_ (
    .clk_2f(clk_2f),
    .clk_8f(clk_8f),
    .clk_8f_in(clk_8f_probador),
    .clk_f(clk_f),
    .resetCLK(resetCLK)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_cond.v:39" *)
  phy_rx_estr phy_rx_estr_ (
    .clk_2f(clk_2f),
    .clk_8f(clk_8f),
    .clk_f(clk_f_negado),
    .data_in_c_0(Paral_serial_out_0_c),
    .data_in_c_1(Paral_serial_out_1_c),
    .data_out_e_0(data_out_e_0),
    .data_out_e_1(data_out_e_1),
    .reset(reset),
    .valid_out_e_0(valid_out_e_0),
    .valid_out_e_1(valid_out_e_1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_cond.v:25" *)
  phy_tx_estr phy_tx_estr_ (
    .Paral_serial_out_0_c(Paral_serial_out_0_c),
    .Paral_serial_out_1_c(Paral_serial_out_1_c),
    .clk_2f(clk_2f),
    .clk_8f(clk_8f),
    .clk_f(clk_f),
    .data_in_0_c(data_in_0_c),
    .data_in_1_c(data_in_1_c),
    .reset(reset),
    .valid_in_0_c(valid_in_0_c),
    .valid_in_1_c(valid_in_1_c)
  );
  assign clk_2f_to_prob_estr = clk_2f;
endmodule

(* src = "phy_rx_estr.v:5" *)
module phy_rx_estr(data_in_c_0, data_in_c_1, clk_f, clk_2f, clk_8f, reset, data_out_e_0, data_out_e_1, valid_out_e_0, valid_out_e_1);
  (* src = "phy_rx_estr.v:23" *)
  wire [7:0] _00_;
  (* src = "phy_rx_estr.v:23" *)
  wire [7:0] _01_;
  (* src = "phy_rx_estr.v:23" *)
  wire _02_;
  (* src = "phy_rx_estr.v:23" *)
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  (* src = "phy_rx_estr.v:9" *)
  input clk_2f;
  (* src = "phy_rx_estr.v:10" *)
  input clk_8f;
  (* src = "phy_rx_estr.v:8" *)
  input clk_f;
  (* src = "phy_rx_estr.v:46" *)
  wire clk_nf;
  (* src = "phy_rx_estr.v:6" *)
  input data_in_c_0;
  (* src = "phy_rx_estr.v:7" *)
  input data_in_c_1;
  (* src = "phy_rx_estr.v:12" *)
  output [7:0] data_out_e_0;
  (* src = "phy_rx_estr.v:18" *)
  wire [7:0] data_out_e_0_aux;
  (* src = "phy_rx_estr.v:13" *)
  output [7:0] data_out_e_1;
  (* src = "phy_rx_estr.v:18" *)
  wire [7:0] data_out_e_1_aux;
  (* src = "phy_rx_estr.v:40" *)
  wire [7:0] data_out_c_US;
  (* src = "phy_rx_estr.v:41" *)
  wire [7:0] lane_c_0;
  (* src = "phy_rx_estr.v:42" *)
  wire [7:0] lane_c_1;
  (* src = "phy_rx_estr.v:11" *)
  input reset;
  (* src = "phy_rx_estr.v:49" *)
  wire reset0;
  (* src = "phy_rx_estr.v:50" *)
  wire reset1;
  (* src = "phy_rx_estr.v:43" *)
  wire valid_c_0_SP;
  (* src = "phy_rx_estr.v:44" *)
  wire valid_c_1_SP;
  (* src = "phy_rx_estr.v:14" *)
  output valid_out_e_0;
  (* src = "phy_rx_estr.v:19" *)
  wire valid_out_e_0_aux;
  (* src = "phy_rx_estr.v:15" *)
  output valid_out_e_1;
  (* src = "phy_rx_estr.v:19" *)
  wire valid_out_e_1_aux;
  (* src = "phy_rx_estr.v:45" *)
  wire valid_out_c_US;
  NOT _22_ (
    .A(clk_f),
    .Y(clk_nf)
  );
  NAND _23_ (
    .A(data_out_e_1_aux[1]),
    .B(reset),
    .Y(_04_)
  );
  NOT _24_ (
    .A(_04_),
    .Y(_01_[1])
  );
  NAND _25_ (
    .A(reset),
    .B(data_out_e_1_aux[2]),
    .Y(_05_)
  );
  NOT _26_ (
    .A(_05_),
    .Y(_01_[2])
  );
  NAND _27_ (
    .A(reset),
    .B(data_out_e_1_aux[3]),
    .Y(_06_)
  );
  NOT _28_ (
    .A(_06_),
    .Y(_01_[3])
  );
  NAND _29_ (
    .A(reset),
    .B(data_out_e_1_aux[4]),
    .Y(_07_)
  );
  NOT _30_ (
    .A(_07_),
    .Y(_01_[4])
  );
  NAND _31_ (
    .A(reset),
    .B(data_out_e_1_aux[5]),
    .Y(_08_)
  );
  NOT _32_ (
    .A(_08_),
    .Y(_01_[5])
  );
  NAND _33_ (
    .A(reset),
    .B(data_out_e_1_aux[6]),
    .Y(_09_)
  );
  NOT _34_ (
    .A(_09_),
    .Y(_01_[6])
  );
  NAND _35_ (
    .A(reset),
    .B(data_out_e_1_aux[7]),
    .Y(_10_)
  );
  NOT _36_ (
    .A(_10_),
    .Y(_01_[7])
  );
  NAND _37_ (
    .A(reset),
    .B(valid_out_e_0_aux),
    .Y(_11_)
  );
  NOT _38_ (
    .A(_11_),
    .Y(_02_)
  );
  NAND _39_ (
    .A(reset),
    .B(data_out_e_0_aux[0]),
    .Y(_12_)
  );
  NOT _40_ (
    .A(_12_),
    .Y(_00_[0])
  );
  NAND _41_ (
    .A(reset),
    .B(data_out_e_0_aux[1]),
    .Y(_13_)
  );
  NOT _42_ (
    .A(_13_),
    .Y(_00_[1])
  );
  NAND _43_ (
    .A(reset),
    .B(data_out_e_0_aux[2]),
    .Y(_14_)
  );
  NOT _44_ (
    .A(_14_),
    .Y(_00_[2])
  );
  NAND _45_ (
    .A(reset),
    .B(data_out_e_0_aux[3]),
    .Y(_15_)
  );
  NOT _46_ (
    .A(_15_),
    .Y(_00_[3])
  );
  NAND _47_ (
    .A(reset),
    .B(data_out_e_0_aux[4]),
    .Y(_16_)
  );
  NOT _48_ (
    .A(_16_),
    .Y(_00_[4])
  );
  NAND _49_ (
    .A(reset),
    .B(data_out_e_0_aux[5]),
    .Y(_17_)
  );
  NOT _50_ (
    .A(_17_),
    .Y(_00_[5])
  );
  NAND _51_ (
    .A(reset),
    .B(data_out_e_0_aux[6]),
    .Y(_18_)
  );
  NOT _52_ (
    .A(_18_),
    .Y(_00_[6])
  );
  NAND _53_ (
    .A(reset),
    .B(data_out_e_0_aux[7]),
    .Y(_19_)
  );
  NOT _54_ (
    .A(_19_),
    .Y(_00_[7])
  );
  NAND _55_ (
    .A(reset),
    .B(valid_out_e_1_aux),
    .Y(_20_)
  );
  NOT _56_ (
    .A(_20_),
    .Y(_03_)
  );
  NAND _57_ (
    .A(reset),
    .B(data_out_e_1_aux[0]),
    .Y(_21_)
  );
  NOT _58_ (
    .A(_21_),
    .Y(_01_[0])
  );
  (* src = "phy_rx_estr.v:53" *)
  DFF _59_ (
    .C(clk_2f),
    .D(reset),
    .Q(reset1)
  );
  (* src = "phy_rx_estr.v:23" *)
  DFF _60_ (
    .C(clk_2f),
    .D(_02_),
    .Q(valid_out_e_0)
  );
  (* src = "phy_rx_estr.v:23" *)
  DFF _61_ (
    .C(clk_2f),
    .D(_03_),
    .Q(valid_out_e_1)
  );
  (* src = "phy_rx_estr.v:23" *)
  DFF _62_ (
    .C(clk_2f),
    .D(_00_[0]),
    .Q(data_out_e_0[0])
  );
  (* src = "phy_rx_estr.v:23" *)
  DFF _63_ (
    .C(clk_2f),
    .D(_00_[1]),
    .Q(data_out_e_0[1])
  );
  (* src = "phy_rx_estr.v:23" *)
  DFF _64_ (
    .C(clk_2f),
    .D(_00_[2]),
    .Q(data_out_e_0[2])
  );
  (* src = "phy_rx_estr.v:23" *)
  DFF _65_ (
    .C(clk_2f),
    .D(_00_[3]),
    .Q(data_out_e_0[3])
  );
  (* src = "phy_rx_estr.v:23" *)
  DFF _66_ (
    .C(clk_2f),
    .D(_00_[4]),
    .Q(data_out_e_0[4])
  );
  (* src = "phy_rx_estr.v:23" *)
  DFF _67_ (
    .C(clk_2f),
    .D(_00_[5]),
    .Q(data_out_e_0[5])
  );
  (* src = "phy_rx_estr.v:23" *)
  DFF _68_ (
    .C(clk_2f),
    .D(_00_[6]),
    .Q(data_out_e_0[6])
  );
  (* src = "phy_rx_estr.v:23" *)
  DFF _69_ (
    .C(clk_2f),
    .D(_00_[7]),
    .Q(data_out_e_0[7])
  );
  (* src = "phy_rx_estr.v:23" *)
  DFF _70_ (
    .C(clk_2f),
    .D(_01_[0]),
    .Q(data_out_e_1[0])
  );
  (* src = "phy_rx_estr.v:23" *)
  DFF _71_ (
    .C(clk_2f),
    .D(_01_[1]),
    .Q(data_out_e_1[1])
  );
  (* src = "phy_rx_estr.v:23" *)
  DFF _72_ (
    .C(clk_2f),
    .D(_01_[2]),
    .Q(data_out_e_1[2])
  );
  (* src = "phy_rx_estr.v:23" *)
  DFF _73_ (
    .C(clk_2f),
    .D(_01_[3]),
    .Q(data_out_e_1[3])
  );
  (* src = "phy_rx_estr.v:23" *)
  DFF _74_ (
    .C(clk_2f),
    .D(_01_[4]),
    .Q(data_out_e_1[4])
  );
  (* src = "phy_rx_estr.v:23" *)
  DFF _75_ (
    .C(clk_2f),
    .D(_01_[5]),
    .Q(data_out_e_1[5])
  );
  (* src = "phy_rx_estr.v:23" *)
  DFF _76_ (
    .C(clk_2f),
    .D(_01_[6]),
    .Q(data_out_e_1[6])
  );
  (* src = "phy_rx_estr.v:23" *)
  DFF _77_ (
    .C(clk_2f),
    .D(_01_[7]),
    .Q(data_out_e_1[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_rx_estr.v:94" *)
  Byte_un_striping_estr Byte_un_striping_instance0 (
    .clk_2f(clk_2f),
    .clk_f(clk_f),
    .data_out_c(data_out_c_US),
    .lane_0(lane_c_0),
    .lane_1(lane_c_1),
    .reset(reset),
    .valid_0(valid_c_0_SP),
    .valid_1(valid_c_1_SP),
    .valid_out_c(valid_out_c_US)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_rx_estr.v:71" *)
  Serie_Paralelo_estructural Serie_Paralelo_estructural_instance0 (
    .clk_8f(clk_8f),
    .clk_f(clk_f),
    .data_in(data_in_c_0),
    .parallel_out_c(lane_c_0),
    .reset(reset),
    .valid_out_c(valid_c_0_SP)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_rx_estr.v:81" *)
  Serie_Paralelo_estructural Serie_Paralelo_estructural_instance1 (
    .clk_8f(clk_8f),
    .clk_f(clk_nf),
    .data_in(data_in_c_1),
    .parallel_out_c(lane_c_1),
    .reset(reset1),
    .valid_out_c(valid_c_1_SP)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_rx_estr.v:109" *)
  demux_estr_estr demux_estr_estr_cond_instance0 (
    .clk2f(clk_2f),
    .clk8f(clk_8f),
    .data_in_c(data_out_c_US),
    .data_out_0_c(data_out_e_0_aux),
    .data_out_1_c(data_out_e_1_aux),
    .reset(reset),
    .valid_in_c(valid_out_c_US),
    .valid_out_0_c(valid_out_e_0_aux),
    .valid_out_1_c(valid_out_e_1_aux)
  );
  assign reset0 = reset;
endmodule

(* src = "phy_tx_estr.v:5" *)
module phy_tx_estr(data_in_0_c, data_in_1_c, valid_in_0_c, valid_in_1_c, clk_f, clk_2f, clk_8f, reset, Paral_serial_out_0_c, Paral_serial_out_1_c);
  (* src = "phy_tx_estr.v:26" *)
  wire [7:0] _00_;
  (* src = "phy_tx_estr.v:26" *)
  wire [7:0] _01_;
  (* src = "phy_tx_estr.v:26" *)
  wire _02_;
  (* src = "phy_tx_estr.v:26" *)
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  (* src = "phy_tx_estr.v:14" *)
  output Paral_serial_out_0_c;
  (* src = "phy_tx_estr.v:15" *)
  output Paral_serial_out_1_c;
  (* src = "phy_tx_estr.v:11" *)
  input clk_2f;
  (* src = "phy_tx_estr.v:12" *)
  input clk_8f;
  (* src = "phy_tx_estr.v:10" *)
  input clk_f;
  (* src = "phy_tx_estr.v:45" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] data2send_c0;
  (* src = "phy_tx_estr.v:46" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] data2send_c1;
  (* src = "phy_tx_estr.v:18" *)
  wire [7:0] data_in_0_FF;
  (* src = "phy_tx_estr.v:6" *)
  input [7:0] data_in_0_c;
  (* src = "phy_tx_estr.v:18" *)
  wire [7:0] data_in_1_FF;
  (* src = "phy_tx_estr.v:7" *)
  input [7:0] data_in_1_c;
  (* src = "phy_tx_estr.v:47" *)
  wire [7:0] data_out_c_mux_estr;
  (* src = "phy_tx_estr.v:48" *)
  wire [7:0] lane_0_c;
  (* src = "phy_tx_estr.v:49" *)
  wire [7:0] lane_1_c;
  (* src = "phy_tx_estr.v:13" *)
  input reset;
  (* src = "phy_tx_estr.v:22" *)
  wire reset0;
  (* src = "phy_tx_estr.v:23" *)
  wire reset1;
  (* src = "phy_tx_estr.v:50" *)
  wire valid_0_c_BS;
  (* src = "phy_tx_estr.v:51" *)
  wire valid_1_c_BS;
  (* src = "phy_tx_estr.v:19" *)
  wire valid_in_0_FF;
  (* src = "phy_tx_estr.v:8" *)
  input valid_in_0_c;
  (* src = "phy_tx_estr.v:19" *)
  wire valid_in_1_FF;
  (* src = "phy_tx_estr.v:9" *)
  input valid_in_1_c;
  (* src = "phy_tx_estr.v:52" *)
  wire valid_mux_estr;
  NAND _22_ (
    .A(data_in_1_c[0]),
    .B(reset),
    .Y(_04_)
  );
  NOT _23_ (
    .A(_04_),
    .Y(_01_[0])
  );
  NAND _24_ (
    .A(reset),
    .B(data_in_1_c[1]),
    .Y(_05_)
  );
  NOT _25_ (
    .A(_05_),
    .Y(_01_[1])
  );
  NAND _26_ (
    .A(reset),
    .B(data_in_1_c[2]),
    .Y(_06_)
  );
  NOT _27_ (
    .A(_06_),
    .Y(_01_[2])
  );
  NAND _28_ (
    .A(reset),
    .B(data_in_1_c[3]),
    .Y(_07_)
  );
  NOT _29_ (
    .A(_07_),
    .Y(_01_[3])
  );
  NAND _30_ (
    .A(reset),
    .B(data_in_1_c[4]),
    .Y(_08_)
  );
  NOT _31_ (
    .A(_08_),
    .Y(_01_[4])
  );
  NAND _32_ (
    .A(reset),
    .B(data_in_1_c[5]),
    .Y(_09_)
  );
  NOT _33_ (
    .A(_09_),
    .Y(_01_[5])
  );
  NAND _34_ (
    .A(reset),
    .B(data_in_1_c[6]),
    .Y(_10_)
  );
  NOT _35_ (
    .A(_10_),
    .Y(_01_[6])
  );
  NAND _36_ (
    .A(reset),
    .B(data_in_1_c[7]),
    .Y(_11_)
  );
  NOT _37_ (
    .A(_11_),
    .Y(_01_[7])
  );
  NAND _38_ (
    .A(reset),
    .B(valid_in_1_c),
    .Y(_12_)
  );
  NOT _39_ (
    .A(_12_),
    .Y(_03_)
  );
  NAND _40_ (
    .A(reset),
    .B(data_in_0_c[0]),
    .Y(_13_)
  );
  NOT _41_ (
    .A(_13_),
    .Y(_00_[0])
  );
  NAND _42_ (
    .A(reset),
    .B(data_in_0_c[1]),
    .Y(_14_)
  );
  NOT _43_ (
    .A(_14_),
    .Y(_00_[1])
  );
  NAND _44_ (
    .A(reset),
    .B(data_in_0_c[2]),
    .Y(_15_)
  );
  NOT _45_ (
    .A(_15_),
    .Y(_00_[2])
  );
  NAND _46_ (
    .A(reset),
    .B(data_in_0_c[3]),
    .Y(_16_)
  );
  NOT _47_ (
    .A(_16_),
    .Y(_00_[3])
  );
  NAND _48_ (
    .A(reset),
    .B(data_in_0_c[4]),
    .Y(_17_)
  );
  NOT _49_ (
    .A(_17_),
    .Y(_00_[4])
  );
  NAND _50_ (
    .A(reset),
    .B(data_in_0_c[5]),
    .Y(_18_)
  );
  NOT _51_ (
    .A(_18_),
    .Y(_00_[5])
  );
  NAND _52_ (
    .A(reset),
    .B(data_in_0_c[6]),
    .Y(_19_)
  );
  NOT _53_ (
    .A(_19_),
    .Y(_00_[6])
  );
  NAND _54_ (
    .A(reset),
    .B(data_in_0_c[7]),
    .Y(_20_)
  );
  NOT _55_ (
    .A(_20_),
    .Y(_00_[7])
  );
  NAND _56_ (
    .A(reset),
    .B(valid_in_0_c),
    .Y(_21_)
  );
  NOT _57_ (
    .A(_21_),
    .Y(_02_)
  );
  (* src = "phy_tx_estr.v:26" *)
  DFF _58_ (
    .C(clk_2f),
    .D(reset),
    .Q(reset1)
  );
  (* src = "phy_tx_estr.v:26" *)
  DFF _59_ (
    .C(clk_2f),
    .D(_00_[0]),
    .Q(data_in_0_FF[0])
  );
  (* src = "phy_tx_estr.v:26" *)
  DFF _60_ (
    .C(clk_2f),
    .D(_00_[1]),
    .Q(data_in_0_FF[1])
  );
  (* src = "phy_tx_estr.v:26" *)
  DFF _61_ (
    .C(clk_2f),
    .D(_00_[2]),
    .Q(data_in_0_FF[2])
  );
  (* src = "phy_tx_estr.v:26" *)
  DFF _62_ (
    .C(clk_2f),
    .D(_00_[3]),
    .Q(data_in_0_FF[3])
  );
  (* src = "phy_tx_estr.v:26" *)
  DFF _63_ (
    .C(clk_2f),
    .D(_00_[4]),
    .Q(data_in_0_FF[4])
  );
  (* src = "phy_tx_estr.v:26" *)
  DFF _64_ (
    .C(clk_2f),
    .D(_00_[5]),
    .Q(data_in_0_FF[5])
  );
  (* src = "phy_tx_estr.v:26" *)
  DFF _65_ (
    .C(clk_2f),
    .D(_00_[6]),
    .Q(data_in_0_FF[6])
  );
  (* src = "phy_tx_estr.v:26" *)
  DFF _66_ (
    .C(clk_2f),
    .D(_00_[7]),
    .Q(data_in_0_FF[7])
  );
  (* src = "phy_tx_estr.v:26" *)
  DFF _67_ (
    .C(clk_2f),
    .D(_02_),
    .Q(valid_in_0_FF)
  );
  (* src = "phy_tx_estr.v:26" *)
  DFF _68_ (
    .C(clk_2f),
    .D(_03_),
    .Q(valid_in_1_FF)
  );
  (* src = "phy_tx_estr.v:26" *)
  DFF _69_ (
    .C(clk_2f),
    .D(_01_[0]),
    .Q(data_in_1_FF[0])
  );
  (* src = "phy_tx_estr.v:26" *)
  DFF _70_ (
    .C(clk_2f),
    .D(_01_[1]),
    .Q(data_in_1_FF[1])
  );
  (* src = "phy_tx_estr.v:26" *)
  DFF _71_ (
    .C(clk_2f),
    .D(_01_[2]),
    .Q(data_in_1_FF[2])
  );
  (* src = "phy_tx_estr.v:26" *)
  DFF _72_ (
    .C(clk_2f),
    .D(_01_[3]),
    .Q(data_in_1_FF[3])
  );
  (* src = "phy_tx_estr.v:26" *)
  DFF _73_ (
    .C(clk_2f),
    .D(_01_[4]),
    .Q(data_in_1_FF[4])
  );
  (* src = "phy_tx_estr.v:26" *)
  DFF _74_ (
    .C(clk_2f),
    .D(_01_[5]),
    .Q(data_in_1_FF[5])
  );
  (* src = "phy_tx_estr.v:26" *)
  DFF _75_ (
    .C(clk_2f),
    .D(_01_[6]),
    .Q(data_in_1_FF[6])
  );
  (* src = "phy_tx_estr.v:26" *)
  DFF _76_ (
    .C(clk_2f),
    .D(_01_[7]),
    .Q(data_in_1_FF[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx_estr.v:70" *)
  Byte_striping_estr Byte_striping_instance0 (
    .clk_2f(clk_2f),
    .data_in(data_out_c_mux_estr),
    .lane_0_c(lane_0_c),
    .lane_1_c(lane_1_c),
    .reset(reset),
    .valid_0_c(valid_0_c_BS),
    .valid_1_c(valid_1_c_BS),
    .valid_in(valid_mux_estr)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx_estr.v:92" *)
  Paralelo_Serie_estructural Paralelo_Serie_estructural_instance0 (
    .clk_8f(clk_8f),
    .clk_f(clk_f),
    .data2send_c(data2send_c0),
    .data_in(lane_0_c),
    .data_out_c(Paral_serial_out_0_c),
    .reset(reset),
    .valid_in(valid_0_c_BS)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx_estr.v:103" *)
  Paralelo_Serie_estructural Paralelo_Serie_estructural_instance1 (
    .clk_8f(clk_8f),
    .clk_f(clk_f),
    .data2send_c(data2send_c1),
    .data_in(lane_1_c),
    .data_out_c(Paral_serial_out_1_c),
    .reset(reset1),
    .valid_in(valid_1_c_BS)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx_estr.v:55" *)
  mux_estr mux_estr_instance0 (
    .clk_2f(clk_2f),
    .clk_8f(clk_8f),
    .data_in_0_c(data_in_0_FF),
    .data_in_1_c(data_in_1_FF),
    .data_out_c(data_out_c_mux_estr),
    .reset(reset),
    .valid_in_0_c(valid_in_0_FF),
    .valid_in_1_c(valid_in_1_FF),
    .valid_out_c(valid_mux_estr)
  );
  assign reset0 = reset;
endmodule
