`include "cmos.v"
/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "Byte_striping_cond.v:1" *)
module Byte_striping_estr(clk_2f, valid_in, data_in, reset, lane_0_e, lane_1_e, valid_0_e, valid_1_e);
  (* src = "Byte_striping_cond.v:80" *)
  wire _000_;
  (* src = "Byte_striping_cond.v:20" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  (* src = "Byte_striping_cond.v:2" *)
  input clk_2f;
  (* src = "Byte_striping_cond.v:4" *)
  input [7:0] data_in;
  (* src = "Byte_striping_cond.v:6" *)
  output [7:0] lane_0_e;
  (* src = "Byte_striping_cond.v:7" *)
  output [7:0] lane_1_e;
  (* src = "Byte_striping_cond.v:5" *)
  input reset;
  (* src = "Byte_striping_cond.v:12" *)
  wire selector;
  (* src = "Byte_striping_cond.v:8" *)
  output valid_0_e;
  (* src = "Byte_striping_cond.v:9" *)
  output valid_1_e;
  (* src = "Byte_striping_cond.v:14" *)
  wire valid_atrasado;
  (* src = "Byte_striping_cond.v:3" *)
  input valid_in;
  (* src = "Byte_striping_cond.v:13" *)
  wire [7:0] y_0;
  (* src = "Byte_striping_cond.v:13" *)
  wire [7:0] y_1;
  NOT _065_ (
    .A(reset),
    .Y(_026_)
  );
  NOR _066_ (
    .A(valid_in),
    .B(selector),
    .Y(_027_)
  );
  NOR _067_ (
    .A(_027_),
    .B(_026_),
    .Y(valid_0_e)
  );
  NOT _068_ (
    .A(valid_in),
    .Y(_028_)
  );
  NOR _069_ (
    .A(_028_),
    .B(selector),
    .Y(_000_)
  );
  NOR _070_ (
    .A(_000_),
    .B(y_0[0]),
    .Y(_029_)
  );
  NOT _071_ (
    .A(data_in[0]),
    .Y(_030_)
  );
  NAND _072_ (
    .A(_000_),
    .B(_030_),
    .Y(_031_)
  );
  NAND _073_ (
    .A(_031_),
    .B(reset),
    .Y(_032_)
  );
  NOR _074_ (
    .A(_032_),
    .B(_029_),
    .Y(lane_0_e[0])
  );
  NOR _075_ (
    .A(_000_),
    .B(y_0[1]),
    .Y(_033_)
  );
  NOT _076_ (
    .A(data_in[1]),
    .Y(_034_)
  );
  NAND _077_ (
    .A(_000_),
    .B(_034_),
    .Y(_035_)
  );
  NAND _078_ (
    .A(_035_),
    .B(reset),
    .Y(_036_)
  );
  NOR _079_ (
    .A(_036_),
    .B(_033_),
    .Y(lane_0_e[1])
  );
  NOR _080_ (
    .A(_000_),
    .B(y_0[2]),
    .Y(_037_)
  );
  NOT _081_ (
    .A(data_in[2]),
    .Y(_038_)
  );
  NAND _082_ (
    .A(_000_),
    .B(_038_),
    .Y(_039_)
  );
  NAND _083_ (
    .A(_039_),
    .B(reset),
    .Y(_040_)
  );
  NOR _084_ (
    .A(_040_),
    .B(_037_),
    .Y(lane_0_e[2])
  );
  NOR _085_ (
    .A(_000_),
    .B(y_0[3]),
    .Y(_041_)
  );
  NOT _086_ (
    .A(data_in[3]),
    .Y(_042_)
  );
  NAND _087_ (
    .A(_000_),
    .B(_042_),
    .Y(_043_)
  );
  NAND _088_ (
    .A(_043_),
    .B(reset),
    .Y(_044_)
  );
  NOR _089_ (
    .A(_044_),
    .B(_041_),
    .Y(lane_0_e[3])
  );
  NOR _090_ (
    .A(_000_),
    .B(y_0[4]),
    .Y(_045_)
  );
  NOT _091_ (
    .A(data_in[4]),
    .Y(_046_)
  );
  NAND _092_ (
    .A(_000_),
    .B(_046_),
    .Y(_047_)
  );
  NAND _093_ (
    .A(_047_),
    .B(reset),
    .Y(_048_)
  );
  NOR _094_ (
    .A(_048_),
    .B(_045_),
    .Y(lane_0_e[4])
  );
  NOR _095_ (
    .A(_000_),
    .B(y_0[5]),
    .Y(_049_)
  );
  NOT _096_ (
    .A(data_in[5]),
    .Y(_050_)
  );
  NAND _097_ (
    .A(_000_),
    .B(_050_),
    .Y(_051_)
  );
  NAND _098_ (
    .A(_051_),
    .B(reset),
    .Y(_052_)
  );
  NOR _099_ (
    .A(_052_),
    .B(_049_),
    .Y(lane_0_e[5])
  );
  NOR _100_ (
    .A(_000_),
    .B(y_0[6]),
    .Y(_053_)
  );
  NOT _101_ (
    .A(data_in[6]),
    .Y(_054_)
  );
  NAND _102_ (
    .A(_000_),
    .B(_054_),
    .Y(_055_)
  );
  NAND _103_ (
    .A(_055_),
    .B(reset),
    .Y(_056_)
  );
  NOR _104_ (
    .A(_056_),
    .B(_053_),
    .Y(lane_0_e[6])
  );
  NOR _105_ (
    .A(_000_),
    .B(y_0[7]),
    .Y(_057_)
  );
  NOT _106_ (
    .A(data_in[7]),
    .Y(_058_)
  );
  NAND _107_ (
    .A(_000_),
    .B(_058_),
    .Y(_059_)
  );
  NAND _108_ (
    .A(_059_),
    .B(reset),
    .Y(_060_)
  );
  NOR _109_ (
    .A(_060_),
    .B(_057_),
    .Y(lane_0_e[7])
  );
  NOT _110_ (
    .A(selector),
    .Y(_061_)
  );
  NOR _111_ (
    .A(valid_in),
    .B(_061_),
    .Y(_062_)
  );
  NAND _112_ (
    .A(reset),
    .B(valid_atrasado),
    .Y(_063_)
  );
  NOR _113_ (
    .A(_063_),
    .B(_062_),
    .Y(valid_1_e)
  );
  NOR _114_ (
    .A(_026_),
    .B(_028_),
    .Y(_001_)
  );
  NOR _115_ (
    .A(_028_),
    .B(_061_),
    .Y(_064_)
  );
  NOR _116_ (
    .A(_064_),
    .B(y_1[0]),
    .Y(_002_)
  );
  NAND _117_ (
    .A(_064_),
    .B(_030_),
    .Y(_003_)
  );
  NAND _118_ (
    .A(_003_),
    .B(reset),
    .Y(_004_)
  );
  NOR _119_ (
    .A(_004_),
    .B(_002_),
    .Y(lane_1_e[0])
  );
  NOR _120_ (
    .A(_064_),
    .B(y_1[1]),
    .Y(_005_)
  );
  NAND _121_ (
    .A(_064_),
    .B(_034_),
    .Y(_006_)
  );
  NAND _122_ (
    .A(_006_),
    .B(reset),
    .Y(_007_)
  );
  NOR _123_ (
    .A(_007_),
    .B(_005_),
    .Y(lane_1_e[1])
  );
  NOR _124_ (
    .A(_064_),
    .B(y_1[2]),
    .Y(_008_)
  );
  NAND _125_ (
    .A(_064_),
    .B(_038_),
    .Y(_009_)
  );
  NAND _126_ (
    .A(_009_),
    .B(reset),
    .Y(_010_)
  );
  NOR _127_ (
    .A(_010_),
    .B(_008_),
    .Y(lane_1_e[2])
  );
  NOR _128_ (
    .A(_064_),
    .B(y_1[3]),
    .Y(_011_)
  );
  NAND _129_ (
    .A(_064_),
    .B(_042_),
    .Y(_012_)
  );
  NAND _130_ (
    .A(_012_),
    .B(reset),
    .Y(_013_)
  );
  NOR _131_ (
    .A(_013_),
    .B(_011_),
    .Y(lane_1_e[3])
  );
  NOR _132_ (
    .A(_064_),
    .B(y_1[4]),
    .Y(_014_)
  );
  NAND _133_ (
    .A(_064_),
    .B(_046_),
    .Y(_015_)
  );
  NAND _134_ (
    .A(_015_),
    .B(reset),
    .Y(_016_)
  );
  NOR _135_ (
    .A(_016_),
    .B(_014_),
    .Y(lane_1_e[4])
  );
  NOR _136_ (
    .A(_064_),
    .B(y_1[5]),
    .Y(_017_)
  );
  NAND _137_ (
    .A(_064_),
    .B(_050_),
    .Y(_018_)
  );
  NAND _138_ (
    .A(_018_),
    .B(reset),
    .Y(_019_)
  );
  NOR _139_ (
    .A(_019_),
    .B(_017_),
    .Y(lane_1_e[5])
  );
  NOR _140_ (
    .A(_064_),
    .B(y_1[6]),
    .Y(_020_)
  );
  NAND _141_ (
    .A(_064_),
    .B(_054_),
    .Y(_021_)
  );
  NAND _142_ (
    .A(_021_),
    .B(reset),
    .Y(_022_)
  );
  NOR _143_ (
    .A(_022_),
    .B(_020_),
    .Y(lane_1_e[6])
  );
  NOR _144_ (
    .A(_064_),
    .B(y_1[7]),
    .Y(_023_)
  );
  NAND _145_ (
    .A(_064_),
    .B(_058_),
    .Y(_024_)
  );
  NAND _146_ (
    .A(_024_),
    .B(reset),
    .Y(_025_)
  );
  NOR _147_ (
    .A(_025_),
    .B(_023_),
    .Y(lane_1_e[7])
  );
  DFF _148_ (
    .C(clk_2f),
    .D(_000_),
    .Q(selector)
  );
  DFF _149_ (
    .C(clk_2f),
    .D(lane_0_e[0]),
    .Q(y_0[0])
  );
  DFF _150_ (
    .C(clk_2f),
    .D(lane_0_e[1]),
    .Q(y_0[1])
  );
  DFF _151_ (
    .C(clk_2f),
    .D(lane_0_e[2]),
    .Q(y_0[2])
  );
  DFF _152_ (
    .C(clk_2f),
    .D(lane_0_e[3]),
    .Q(y_0[3])
  );
  DFF _153_ (
    .C(clk_2f),
    .D(lane_0_e[4]),
    .Q(y_0[4])
  );
  DFF _154_ (
    .C(clk_2f),
    .D(lane_0_e[5]),
    .Q(y_0[5])
  );
  DFF _155_ (
    .C(clk_2f),
    .D(lane_0_e[6]),
    .Q(y_0[6])
  );
  DFF _156_ (
    .C(clk_2f),
    .D(lane_0_e[7]),
    .Q(y_0[7])
  );
  DFF _157_ (
    .C(clk_2f),
    .D(lane_1_e[0]),
    .Q(y_1[0])
  );
  DFF _158_ (
    .C(clk_2f),
    .D(lane_1_e[1]),
    .Q(y_1[1])
  );
  DFF _159_ (
    .C(clk_2f),
    .D(lane_1_e[2]),
    .Q(y_1[2])
  );
  DFF _160_ (
    .C(clk_2f),
    .D(lane_1_e[3]),
    .Q(y_1[3])
  );
  DFF _161_ (
    .C(clk_2f),
    .D(lane_1_e[4]),
    .Q(y_1[4])
  );
  DFF _162_ (
    .C(clk_2f),
    .D(lane_1_e[5]),
    .Q(y_1[5])
  );
  DFF _163_ (
    .C(clk_2f),
    .D(lane_1_e[6]),
    .Q(y_1[6])
  );
  DFF _164_ (
    .C(clk_2f),
    .D(lane_1_e[7]),
    .Q(y_1[7])
  );
  DFF _165_ (
    .C(clk_2f),
    .D(_001_),
    .Q(valid_atrasado)
  );
endmodule
