/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "Paralelo_Serie_conductual.v:3" *)
module P_S_Yosys(clk_8f, clk_f, data_in, valid_in, reset,  data2send_e,  data_out_e);
  (* src = "Paralelo_Serie_conductual.v:23" *)
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  (* src = "Paralelo_Serie_conductual.v:3" *)
  input clk_8f;
  (* src = "Paralelo_Serie_conductual.v:4" *)
  input clk_f;
  (* src = "Paralelo_Serie_conductual.v:8" *)
  output [7:0]  data2send_e;
  (* src = "Paralelo_Serie_conductual.v:5" *)
  input [7:0] data_in;
  (* src = "Paralelo_Serie_conductual.v:9" *)
  output  data_out_e;
  (* src = "Paralelo_Serie_conductual.v:10" *)
  wire [2:0] j;
  (* src = "Paralelo_Serie_conductual.v:7" *)
  input reset;
  (* src = "Paralelo_Serie_conductual.v:6" *)
  input valid_in;
  NAND _42_ (
    .A(data_in[1]),
    .B(valid_in),
    .Y(_01_)
  );
  NOT _43_ (
    .A(_01_),
    .Y( data2send_e[1])
  );
  NOT _44_ (
    .A(data_in[5]),
    .Y(_02_)
  );
  NAND _45_ (
    .A(_02_),
    .B(valid_in),
    .Y( data2send_e[5])
  );
  NOT _46_ (
    .A(data_in[2]),
    .Y(_03_)
  );
  NAND _47_ (
    .A(_03_),
    .B(valid_in),
    .Y( data2send_e[2])
  );
  NOT _48_ (
    .A(valid_in),
    .Y(_04_)
  );
  NOT _49_ (
    .A(data_in[6]),
    .Y(_05_)
  );
  NOR _50_ (
    .A(_05_),
    .B(_04_),
    .Y( data2send_e[6])
  );
  NOT _51_ (
    .A(data_in[3]),
    .Y(_06_)
  );
  NAND _52_ (
    .A(_06_),
    .B(valid_in),
    .Y( data2send_e[3])
  );
  NOT _53_ (
    .A(data_in[7]),
    .Y(_07_)
  );
  NAND _54_ (
    .A(_07_),
    .B(valid_in),
    .Y( data2send_e[7])
  );
  NAND _55_ (
    .A(valid_in),
    .B(data_in[0]),
    .Y(_08_)
  );
  NOT _56_ (
    .A(_08_),
    .Y( data2send_e[0])
  );
  NOT _57_ (
    .A(data_in[4]),
    .Y(_09_)
  );
  NAND _58_ (
    .A(_09_),
    .B(valid_in),
    .Y( data2send_e[4])
  );
  NAND _59_ (
    .A(reset),
    .B(j[0]),
    .Y(_00_[0])
  );
  NOR _60_ (
    .A(j[1]),
    .B(j[0]),
    .Y(_10_)
  );
  NOT _61_ (
    .A(_10_),
    .Y(_11_)
  );
  NOT _62_ (
    .A(reset),
    .Y(_12_)
  );
  NOT _63_ (
    .A(j[0]),
    .Y(_13_)
  );
  NOT _64_ (
    .A(j[1]),
    .Y(_14_)
  );
  NOR _65_ (
    .A(_14_),
    .B(_13_),
    .Y(_15_)
  );
  NOR _66_ (
    .A(_15_),
    .B(_12_),
    .Y(_16_)
  );
  NAND _67_ (
    .A(_16_),
    .B(_11_),
    .Y(_00_[1])
  );
  NOT _68_ (
    .A(j[2]),
    .Y(_17_)
  );
  NAND _69_ (
    .A(_10_),
    .B(_17_),
    .Y(_18_)
  );
  NOR _70_ (
    .A(_10_),
    .B(_17_),
    .Y(_19_)
  );
  NOR _71_ (
    .A(_19_),
    .B(_12_),
    .Y(_20_)
  );
  NAND _72_ (
    .A(_20_),
    .B(_18_),
    .Y(_00_[2])
  );
  NAND _73_ (
    .A( data2send_e[7]),
    .B(j[2]),
    .Y(_21_)
  );
  NAND _74_ (
    .A( data2send_e[3]),
    .B(_17_),
    .Y(_22_)
  );
  NAND _75_ (
    .A(_22_),
    .B(_21_),
    .Y(_23_)
  );
  NAND _76_ (
    .A(_23_),
    .B(j[0]),
    .Y(_24_)
  );
  NOR _77_ (
    .A( data2send_e[2]),
    .B(j[2]),
    .Y(_25_)
  );
  NOR _78_ (
    .A( data2send_e[6]),
    .B(_17_),
    .Y(_26_)
  );
  NOR _79_ (
    .A(_26_),
    .B(_25_),
    .Y(_27_)
  );
  NAND _80_ (
    .A(_27_),
    .B(_13_),
    .Y(_28_)
  );
  NAND _81_ (
    .A(_28_),
    .B(_24_),
    .Y(_29_)
  );
  NOR _82_ (
    .A(_29_),
    .B(_14_),
    .Y(_30_)
  );
  NOR _83_ (
    .A( data2send_e[5]),
    .B(_17_),
    .Y(_31_)
  );
  NAND _84_ (
    .A(_01_),
    .B(_17_),
    .Y(_32_)
  );
  NAND _85_ (
    .A(_32_),
    .B(j[0]),
    .Y(_33_)
  );
  NOR _86_ (
    .A(_33_),
    .B(_31_),
    .Y(_34_)
  );
  NOR _87_ (
    .A( data2send_e[4]),
    .B(_17_),
    .Y(_35_)
  );
  NAND _88_ (
    .A(_08_),
    .B(_17_),
    .Y(_36_)
  );
  NAND _89_ (
    .A(_36_),
    .B(_13_),
    .Y(_37_)
  );
  NOR _90_ (
    .A(_37_),
    .B(_35_),
    .Y(_38_)
  );
  NOR _91_ (
    .A(_38_),
    .B(_34_),
    .Y(_39_)
  );
  NAND _92_ (
    .A(_39_),
    .B(_14_),
    .Y(_40_)
  );
  NAND _93_ (
    .A(_40_),
    .B(reset),
    .Y(_41_)
  );
  NOR _94_ (
    .A(_41_),
    .B(_30_),
    .Y( data_out_e)
  );
  DFF _95_ (
    .C(clk_8f),
    .D(_00_[0]),
    .Q(j[0])
  );
  DFF _96_ (
    .C(clk_8f),
    .D(_00_[1]),
    .Q(j[1])
  );
  DFF _97_ (
    .C(clk_8f),
    .D(_00_[2]),
    .Q(j[2])
  );
endmodule
