`include "cmos_cells.v"
/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* src = "clkgen.v:1" *)
module clkgen_s(clkf, clk2f, clk4f, clk8f, reset);
  (* src = "clkgen.v:12" *)
  wire _0_;
  wire _1_;
  (* src = "clkgen.v:3" *)
  output clk2f;
  (* src = "clkgen.v:4" *)
  output clk4f;
  (* src = "clkgen.v:5" *)
  input clk8f;
  (* src = "clkgen.v:2" *)
  output clkf;
  (* src = "clkgen.v:6" *)
  input reset;
  NOT _2_ (
    .A(reset),
    .Y(_1_)
  );
  NOR _3_ (
    .A(_1_),
    .B(clk4f),
    .Y(_0_)
  );
  DFF _4_ (
    .C(clk8f),
    .D(_0_),
    .Q(clk4f)
  );
  assign clk2f = 1'b0;
  assign clkf = 1'b0;
endmodule

(* top =  1  *)
(* src = "proy1_conductual.v:3" *)
module proy1_synth(clk8f, clk2f_s, clk4f_s, clkf_s, reset);
  (* src = "proy1_conductual.v:5" *)
  output clk2f_s;
  (* src = "proy1_conductual.v:6" *)
  output clk4f_s;
  (* src = "proy1_conductual.v:4" *)
  input clk8f;
  (* src = "proy1_conductual.v:7" *)
  output clkf_s;
  (* src = "proy1_conductual.v:8" *)
  input reset;
  (* src = "proy1_conductual.v:10" *)
  clkgen generador_de_relojes (
    .clk2f(clk2f_s),
    .clk4f(clk4f_s),
    .clk8f(clk8f),
    .clkf(clkf_s),
    .reset(reset)
  );
endmodule
