/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "FSM_e.v:2" *)
module FSM_e(clk, reset, init, UMF, UVC, UD, FIFO_ERROR, FIFO_EMPTY, error_out_e, active_out_e, idle_out_e, UMF_OUT_e, UVC_OUT_e, UD_OUT_e);
  (* src = "FSM_e.v:36" *)
  wire [7:0] _000_;
  (* src = "FSM_e.v:36" *)
  wire [7:0] _001_;
  (* src = "FSM_e.v:36" *)
  wire [7:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  (* src = "FSM_e.v:9" *)
  input [4:0] FIFO_EMPTY;
  (* src = "FSM_e.v:8" *)
  input [4:0] FIFO_ERROR;
  (* src = "FSM_e.v:7" *)
  input [7:0] UD;
  (* src = "FSM_e.v:15" *)
  output [7:0] UD_OUT_e;
  (* src = "FSM_e.v:5" *)
  input [7:0] UMF;
  (* src = "FSM_e.v:13" *)
  output [7:0] UMF_OUT_e;
  (* src = "FSM_e.v:6" *)
  input [7:0] UVC;
  (* src = "FSM_e.v:14" *)
  output [7:0] UVC_OUT_e;
  (* src = "FSM_e.v:11" *)
  output active_out_e;
  (* src = "FSM_e.v:2" *)
  input clk;
  (* src = "FSM_e.v:10" *)
  output error_out_e;
  (* onehot = 32'd1 *)
  wire [4:0] estado;
  (* src = "FSM_e.v:12" *)
  output idle_out_e;
  (* src = "FSM_e.v:4" *)
  input init;
  (* src = "FSM_e.v:3" *)
  input reset;
  NOT _090_ (
    .A(init),
    .Y(_086_)
  );
  NAND _091_ (
    .A(estado[0]),
    .B(_086_),
    .Y(_087_)
  );
  NAND _092_ (
    .A(_087_),
    .B(reset),
    .Y(_078_)
  );
  NOT _093_ (
    .A(reset),
    .Y(_088_)
  );
  NOT _094_ (
    .A(estado[0]),
    .Y(_089_)
  );
  NOT _095_ (
    .A(FIFO_ERROR[0]),
    .Y(_003_)
  );
  NOT _096_ (
    .A(FIFO_ERROR[1]),
    .Y(_004_)
  );
  NAND _097_ (
    .A(_004_),
    .B(_003_),
    .Y(_005_)
  );
  NOT _098_ (
    .A(FIFO_ERROR[4]),
    .Y(_006_)
  );
  NOR _099_ (
    .A(FIFO_ERROR[3]),
    .B(FIFO_ERROR[2]),
    .Y(_007_)
  );
  NAND _100_ (
    .A(_007_),
    .B(_006_),
    .Y(_008_)
  );
  NOR _101_ (
    .A(_008_),
    .B(_005_),
    .Y(_009_)
  );
  NAND _102_ (
    .A(_009_),
    .B(estado[2]),
    .Y(_010_)
  );
  NAND _103_ (
    .A(_010_),
    .B(_089_),
    .Y(_011_)
  );
  NAND _104_ (
    .A(_011_),
    .B(init),
    .Y(_012_)
  );
  NOR _105_ (
    .A(_012_),
    .B(_088_),
    .Y(_083_)
  );
  NOR _106_ (
    .A(_010_),
    .B(init),
    .Y(_013_)
  );
  NOT _107_ (
    .A(estado[3]),
    .Y(_014_)
  );
  NOT _108_ (
    .A(FIFO_EMPTY[0]),
    .Y(_015_)
  );
  NOT _109_ (
    .A(FIFO_EMPTY[1]),
    .Y(_016_)
  );
  NAND _110_ (
    .A(_016_),
    .B(_015_),
    .Y(_017_)
  );
  NOT _111_ (
    .A(FIFO_EMPTY[4]),
    .Y(_018_)
  );
  NOR _112_ (
    .A(FIFO_EMPTY[3]),
    .B(FIFO_EMPTY[2]),
    .Y(_019_)
  );
  NAND _113_ (
    .A(_019_),
    .B(_018_),
    .Y(_020_)
  );
  NOR _114_ (
    .A(_020_),
    .B(_017_),
    .Y(_021_)
  );
  NOR _115_ (
    .A(_021_),
    .B(_014_),
    .Y(_022_)
  );
  NOR _116_ (
    .A(_022_),
    .B(_013_),
    .Y(_023_)
  );
  NOR _117_ (
    .A(_023_),
    .B(_088_),
    .Y(_084_)
  );
  NOR _118_ (
    .A(FIFO_EMPTY[4]),
    .B(FIFO_EMPTY[2]),
    .Y(_024_)
  );
  NOR _119_ (
    .A(_017_),
    .B(FIFO_EMPTY[3]),
    .Y(_025_)
  );
  NAND _120_ (
    .A(_025_),
    .B(_024_),
    .Y(_027_)
  );
  NOR _121_ (
    .A(_027_),
    .B(_014_),
    .Y(_028_)
  );
  NOR _122_ (
    .A(_028_),
    .B(estado[4]),
    .Y(_029_)
  );
  NOR _123_ (
    .A(_029_),
    .B(_088_),
    .Y(_085_)
  );
  NAND _124_ (
    .A(estado[4]),
    .B(UD[0]),
    .Y(_030_)
  );
  NOT _125_ (
    .A(estado[4]),
    .Y(_031_)
  );
  NAND _126_ (
    .A(_031_),
    .B(UD_OUT_e[0]),
    .Y(_032_)
  );
  NAND _127_ (
    .A(_032_),
    .B(_030_),
    .Y(_000_[0])
  );
  NAND _128_ (
    .A(UD[1]),
    .B(estado[4]),
    .Y(_033_)
  );
  NAND _129_ (
    .A(UD_OUT_e[1]),
    .B(_031_),
    .Y(_034_)
  );
  NAND _130_ (
    .A(_034_),
    .B(_033_),
    .Y(_000_[1])
  );
  NAND _131_ (
    .A(UD[2]),
    .B(estado[4]),
    .Y(_035_)
  );
  NAND _132_ (
    .A(UD_OUT_e[2]),
    .B(_031_),
    .Y(_036_)
  );
  NAND _133_ (
    .A(_036_),
    .B(_035_),
    .Y(_000_[2])
  );
  NAND _134_ (
    .A(UD[3]),
    .B(estado[4]),
    .Y(_037_)
  );
  NAND _135_ (
    .A(UD_OUT_e[3]),
    .B(_031_),
    .Y(_038_)
  );
  NAND _136_ (
    .A(_038_),
    .B(_037_),
    .Y(_000_[3])
  );
  NAND _137_ (
    .A(UD[4]),
    .B(estado[4]),
    .Y(_039_)
  );
  NAND _138_ (
    .A(UD_OUT_e[4]),
    .B(_031_),
    .Y(_040_)
  );
  NAND _139_ (
    .A(_040_),
    .B(_039_),
    .Y(_000_[4])
  );
  NAND _140_ (
    .A(UD[5]),
    .B(estado[4]),
    .Y(_041_)
  );
  NAND _141_ (
    .A(UD_OUT_e[5]),
    .B(_031_),
    .Y(_042_)
  );
  NAND _142_ (
    .A(_042_),
    .B(_041_),
    .Y(_000_[5])
  );
  NAND _143_ (
    .A(UD[6]),
    .B(estado[4]),
    .Y(_043_)
  );
  NAND _144_ (
    .A(UD_OUT_e[6]),
    .B(_031_),
    .Y(_044_)
  );
  NAND _145_ (
    .A(_044_),
    .B(_043_),
    .Y(_000_[6])
  );
  NAND _146_ (
    .A(UD[7]),
    .B(estado[4]),
    .Y(_045_)
  );
  NAND _147_ (
    .A(UD_OUT_e[7]),
    .B(_031_),
    .Y(_046_)
  );
  NAND _148_ (
    .A(_046_),
    .B(_045_),
    .Y(_000_[7])
  );
  NAND _149_ (
    .A(UVC[0]),
    .B(estado[4]),
    .Y(_047_)
  );
  NAND _150_ (
    .A(UVC_OUT_e[0]),
    .B(_031_),
    .Y(_048_)
  );
  NAND _151_ (
    .A(_048_),
    .B(_047_),
    .Y(_002_[0])
  );
  NAND _152_ (
    .A(UVC[1]),
    .B(estado[4]),
    .Y(_049_)
  );
  NAND _153_ (
    .A(UVC_OUT_e[1]),
    .B(_031_),
    .Y(_050_)
  );
  NAND _154_ (
    .A(_050_),
    .B(_049_),
    .Y(_002_[1])
  );
  NAND _155_ (
    .A(UVC[2]),
    .B(estado[4]),
    .Y(_051_)
  );
  NAND _156_ (
    .A(UVC_OUT_e[2]),
    .B(_031_),
    .Y(_052_)
  );
  NAND _157_ (
    .A(_052_),
    .B(_051_),
    .Y(_002_[2])
  );
  NAND _158_ (
    .A(UVC[3]),
    .B(estado[4]),
    .Y(_053_)
  );
  NAND _159_ (
    .A(UVC_OUT_e[3]),
    .B(_031_),
    .Y(_054_)
  );
  NAND _160_ (
    .A(_054_),
    .B(_053_),
    .Y(_002_[3])
  );
  NAND _161_ (
    .A(UVC[4]),
    .B(estado[4]),
    .Y(_055_)
  );
  NAND _162_ (
    .A(UVC_OUT_e[4]),
    .B(_031_),
    .Y(_056_)
  );
  NAND _163_ (
    .A(_056_),
    .B(_055_),
    .Y(_002_[4])
  );
  NAND _164_ (
    .A(UVC[5]),
    .B(estado[4]),
    .Y(_057_)
  );
  NAND _165_ (
    .A(UVC_OUT_e[5]),
    .B(_031_),
    .Y(_058_)
  );
  NAND _166_ (
    .A(_058_),
    .B(_057_),
    .Y(_002_[5])
  );
  NAND _167_ (
    .A(UVC[6]),
    .B(estado[4]),
    .Y(_059_)
  );
  NAND _168_ (
    .A(UVC_OUT_e[6]),
    .B(_031_),
    .Y(_060_)
  );
  NAND _169_ (
    .A(_060_),
    .B(_059_),
    .Y(_002_[6])
  );
  NAND _170_ (
    .A(UVC[7]),
    .B(estado[4]),
    .Y(_061_)
  );
  NAND _171_ (
    .A(UVC_OUT_e[7]),
    .B(_031_),
    .Y(_062_)
  );
  NAND _172_ (
    .A(_062_),
    .B(_061_),
    .Y(_002_[7])
  );
  NAND _173_ (
    .A(UMF[0]),
    .B(estado[4]),
    .Y(_063_)
  );
  NAND _174_ (
    .A(UMF_OUT_e[0]),
    .B(_031_),
    .Y(_064_)
  );
  NAND _175_ (
    .A(_064_),
    .B(_063_),
    .Y(_001_[0])
  );
  NAND _176_ (
    .A(UMF[1]),
    .B(estado[4]),
    .Y(_065_)
  );
  NAND _177_ (
    .A(UMF_OUT_e[1]),
    .B(_031_),
    .Y(_066_)
  );
  NAND _178_ (
    .A(_066_),
    .B(_065_),
    .Y(_001_[1])
  );
  NAND _179_ (
    .A(UMF[2]),
    .B(estado[4]),
    .Y(_067_)
  );
  NAND _180_ (
    .A(UMF_OUT_e[2]),
    .B(_031_),
    .Y(_068_)
  );
  NAND _181_ (
    .A(_068_),
    .B(_067_),
    .Y(_001_[2])
  );
  NAND _182_ (
    .A(UMF[3]),
    .B(estado[4]),
    .Y(_069_)
  );
  NAND _183_ (
    .A(UMF_OUT_e[3]),
    .B(_031_),
    .Y(_070_)
  );
  NAND _184_ (
    .A(_070_),
    .B(_069_),
    .Y(_001_[3])
  );
  NAND _185_ (
    .A(UMF[4]),
    .B(estado[4]),
    .Y(_071_)
  );
  NAND _186_ (
    .A(UMF_OUT_e[4]),
    .B(_031_),
    .Y(_072_)
  );
  NAND _187_ (
    .A(_072_),
    .B(_071_),
    .Y(_001_[4])
  );
  NAND _188_ (
    .A(UMF[5]),
    .B(estado[4]),
    .Y(_073_)
  );
  NAND _189_ (
    .A(UMF_OUT_e[5]),
    .B(_031_),
    .Y(_074_)
  );
  NAND _190_ (
    .A(_074_),
    .B(_073_),
    .Y(_001_[5])
  );
  NAND _191_ (
    .A(UMF[6]),
    .B(estado[4]),
    .Y(_075_)
  );
  NAND _192_ (
    .A(UMF_OUT_e[6]),
    .B(_031_),
    .Y(_076_)
  );
  NAND _193_ (
    .A(_076_),
    .B(_075_),
    .Y(_001_[6])
  );
  NAND _194_ (
    .A(UMF[7]),
    .B(estado[4]),
    .Y(_077_)
  );
  NAND _195_ (
    .A(UMF_OUT_e[7]),
    .B(_031_),
    .Y(_079_)
  );
  NAND _196_ (
    .A(_079_),
    .B(_077_),
    .Y(_001_[7])
  );
  NOT _197_ (
    .A(estado[2]),
    .Y(_080_)
  );
  NOR _198_ (
    .A(_009_),
    .B(_080_),
    .Y(_081_)
  );
  NOR _199_ (
    .A(_081_),
    .B(estado[1]),
    .Y(_082_)
  );
  NOR _200_ (
    .A(_082_),
    .B(_088_),
    .Y(_026_)
  );
  DFF _201_ (
    .C(clk),
    .D(_078_),
    .Q(estado[0])
  );
  DFF _202_ (
    .C(clk),
    .D(_026_),
    .Q(estado[1])
  );
  DFF _203_ (
    .C(clk),
    .D(_084_),
    .Q(estado[2])
  );
  DFF _204_ (
    .C(clk),
    .D(_085_),
    .Q(estado[3])
  );
  DFF _205_ (
    .C(clk),
    .D(_083_),
    .Q(estado[4])
  );
  DFF _206_ (
    .C(clk),
    .D(_001_[0]),
    .Q(UMF_OUT_e[0])
  );
  DFF _207_ (
    .C(clk),
    .D(_001_[1]),
    .Q(UMF_OUT_e[1])
  );
  DFF _208_ (
    .C(clk),
    .D(_001_[2]),
    .Q(UMF_OUT_e[2])
  );
  DFF _209_ (
    .C(clk),
    .D(_001_[3]),
    .Q(UMF_OUT_e[3])
  );
  DFF _210_ (
    .C(clk),
    .D(_001_[4]),
    .Q(UMF_OUT_e[4])
  );
  DFF _211_ (
    .C(clk),
    .D(_001_[5]),
    .Q(UMF_OUT_e[5])
  );
  DFF _212_ (
    .C(clk),
    .D(_001_[6]),
    .Q(UMF_OUT_e[6])
  );
  DFF _213_ (
    .C(clk),
    .D(_001_[7]),
    .Q(UMF_OUT_e[7])
  );
  DFF _214_ (
    .C(clk),
    .D(_002_[0]),
    .Q(UVC_OUT_e[0])
  );
  DFF _215_ (
    .C(clk),
    .D(_002_[1]),
    .Q(UVC_OUT_e[1])
  );
  DFF _216_ (
    .C(clk),
    .D(_002_[2]),
    .Q(UVC_OUT_e[2])
  );
  DFF _217_ (
    .C(clk),
    .D(_002_[3]),
    .Q(UVC_OUT_e[3])
  );
  DFF _218_ (
    .C(clk),
    .D(_002_[4]),
    .Q(UVC_OUT_e[4])
  );
  DFF _219_ (
    .C(clk),
    .D(_002_[5]),
    .Q(UVC_OUT_e[5])
  );
  DFF _220_ (
    .C(clk),
    .D(_002_[6]),
    .Q(UVC_OUT_e[6])
  );
  DFF _221_ (
    .C(clk),
    .D(_002_[7]),
    .Q(UVC_OUT_e[7])
  );
  DFF _222_ (
    .C(clk),
    .D(_000_[0]),
    .Q(UD_OUT_e[0])
  );
  DFF _223_ (
    .C(clk),
    .D(_000_[1]),
    .Q(UD_OUT_e[1])
  );
  DFF _224_ (
    .C(clk),
    .D(_000_[2]),
    .Q(UD_OUT_e[2])
  );
  DFF _225_ (
    .C(clk),
    .D(_000_[3]),
    .Q(UD_OUT_e[3])
  );
  DFF _226_ (
    .C(clk),
    .D(_000_[4]),
    .Q(UD_OUT_e[4])
  );
  DFF _227_ (
    .C(clk),
    .D(_000_[5]),
    .Q(UD_OUT_e[5])
  );
  DFF _228_ (
    .C(clk),
    .D(_000_[6]),
    .Q(UD_OUT_e[6])
  );
  DFF _229_ (
    .C(clk),
    .D(_000_[7]),
    .Q(UD_OUT_e[7])
  );
  assign active_out_e = estado[2];
  assign error_out_e = estado[1];
  assign idle_out_e = estado[3];
endmodule
