`include "cmos.v"
/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "Byte_un_striping_cond.v:1" *)
module Byte_un_striping_estr(clk_f, clk_2f, lane_0, lane_1, valid_0, valid_1, reset, data_out_e, valid_out_e);
  (* src = "Byte_un_striping_cond.v:15" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  (* src = "Byte_un_striping_cond.v:3" *)
  input clk_2f;
  (* src = "Byte_un_striping_cond.v:2" *)
  input clk_f;
  (* src = "Byte_un_striping_cond.v:13" *)
  wire control;
  (* src = "Byte_un_striping_cond.v:9" *)
  output [7:0] data_out_e;
  (* src = "Byte_un_striping_cond.v:4" *)
  input [7:0] lane_0;
  (* src = "Byte_un_striping_cond.v:5" *)
  input [7:0] lane_1;
  (* src = "Byte_un_striping_cond.v:8" *)
  input reset;
  (* src = "Byte_un_striping_cond.v:6" *)
  input valid_0;
  (* src = "Byte_un_striping_cond.v:7" *)
  input valid_1;
  (* src = "Byte_un_striping_cond.v:10" *)
  output valid_out_e;
  NOR _39_ (
    .A(lane_0[0]),
    .B(control),
    .Y(_01_)
  );
  NOT _40_ (
    .A(valid_0),
    .Y(_02_)
  );
  NOT _41_ (
    .A(reset),
    .Y(_03_)
  );
  NOR _42_ (
    .A(_03_),
    .B(_02_),
    .Y(valid_out_e)
  );
  NOT _43_ (
    .A(lane_1[0]),
    .Y(_04_)
  );
  NAND _44_ (
    .A(_04_),
    .B(control),
    .Y(_05_)
  );
  NAND _45_ (
    .A(_05_),
    .B(valid_out_e),
    .Y(_06_)
  );
  NOR _46_ (
    .A(_06_),
    .B(_01_),
    .Y(data_out_e[0])
  );
  NOR _47_ (
    .A(lane_0[1]),
    .B(control),
    .Y(_07_)
  );
  NOT _48_ (
    .A(lane_1[1]),
    .Y(_08_)
  );
  NAND _49_ (
    .A(_08_),
    .B(control),
    .Y(_09_)
  );
  NAND _50_ (
    .A(_09_),
    .B(valid_out_e),
    .Y(_10_)
  );
  NOR _51_ (
    .A(_10_),
    .B(_07_),
    .Y(data_out_e[1])
  );
  NOR _52_ (
    .A(lane_0[2]),
    .B(control),
    .Y(_11_)
  );
  NOT _53_ (
    .A(lane_1[2]),
    .Y(_12_)
  );
  NAND _54_ (
    .A(_12_),
    .B(control),
    .Y(_13_)
  );
  NAND _55_ (
    .A(_13_),
    .B(valid_out_e),
    .Y(_14_)
  );
  NOR _56_ (
    .A(_14_),
    .B(_11_),
    .Y(data_out_e[2])
  );
  NOR _57_ (
    .A(lane_0[3]),
    .B(control),
    .Y(_15_)
  );
  NOT _58_ (
    .A(lane_1[3]),
    .Y(_16_)
  );
  NAND _59_ (
    .A(_16_),
    .B(control),
    .Y(_17_)
  );
  NAND _60_ (
    .A(_17_),
    .B(valid_out_e),
    .Y(_18_)
  );
  NOR _61_ (
    .A(_18_),
    .B(_15_),
    .Y(data_out_e[3])
  );
  NOR _62_ (
    .A(lane_0[4]),
    .B(control),
    .Y(_19_)
  );
  NOT _63_ (
    .A(lane_1[4]),
    .Y(_20_)
  );
  NAND _64_ (
    .A(_20_),
    .B(control),
    .Y(_21_)
  );
  NAND _65_ (
    .A(_21_),
    .B(valid_out_e),
    .Y(_22_)
  );
  NOR _66_ (
    .A(_22_),
    .B(_19_),
    .Y(data_out_e[4])
  );
  NOR _67_ (
    .A(lane_0[5]),
    .B(control),
    .Y(_23_)
  );
  NOT _68_ (
    .A(lane_1[5]),
    .Y(_24_)
  );
  NAND _69_ (
    .A(_24_),
    .B(control),
    .Y(_25_)
  );
  NAND _70_ (
    .A(_25_),
    .B(valid_out_e),
    .Y(_26_)
  );
  NOR _71_ (
    .A(_26_),
    .B(_23_),
    .Y(data_out_e[5])
  );
  NOR _72_ (
    .A(lane_0[6]),
    .B(control),
    .Y(_27_)
  );
  NOT _73_ (
    .A(lane_1[6]),
    .Y(_28_)
  );
  NAND _74_ (
    .A(_28_),
    .B(control),
    .Y(_29_)
  );
  NAND _75_ (
    .A(_29_),
    .B(valid_out_e),
    .Y(_30_)
  );
  NOR _76_ (
    .A(_30_),
    .B(_27_),
    .Y(data_out_e[6])
  );
  NOR _77_ (
    .A(lane_0[7]),
    .B(control),
    .Y(_31_)
  );
  NOT _78_ (
    .A(lane_1[7]),
    .Y(_32_)
  );
  NAND _79_ (
    .A(_32_),
    .B(control),
    .Y(_33_)
  );
  NAND _80_ (
    .A(_33_),
    .B(valid_out_e),
    .Y(_34_)
  );
  NOR _81_ (
    .A(_34_),
    .B(_31_),
    .Y(data_out_e[7])
  );
  NOT _82_ (
    .A(control),
    .Y(_35_)
  );
  NOT _83_ (
    .A(valid_1),
    .Y(_36_)
  );
  NAND _84_ (
    .A(_36_),
    .B(_02_),
    .Y(_37_)
  );
  NAND _85_ (
    .A(_37_),
    .B(_35_),
    .Y(_38_)
  );
  NAND _86_ (
    .A(_38_),
    .B(reset),
    .Y(_00_)
  );
  DFF _87_ (
    .C(clk_2f),
    .D(_00_),
    .Q(control)
  );
endmodule
