`include "cmos.v"
/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "Byte_un_striping_cond.v:1" *)
module Byte_un_striping_estr(clk_f, clk_2f, lane_0, lane_1, valid_0, valid_1, reset, data_out_e, valid_out_e);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  (* src = "Byte_un_striping_cond.v:3" *)
  input clk_2f;
  (* src = "Byte_un_striping_cond.v:2" *)
  input clk_f;
  (* src = "Byte_un_striping_cond.v:9" *)
  output [7:0] data_out_e;
  (* onehot = 32'd1 *)
  wire [3:0] estado;
  (* src = "Byte_un_striping_cond.v:4" *)
  input [7:0] lane_0;
  (* src = "Byte_un_striping_cond.v:5" *)
  input [7:0] lane_1;
  (* src = "Byte_un_striping_cond.v:8" *)
  input reset;
  (* src = "Byte_un_striping_cond.v:6" *)
  input valid_0;
  (* src = "Byte_un_striping_cond.v:7" *)
  input valid_1;
  (* src = "Byte_un_striping_cond.v:10" *)
  output valid_out_e;
  NOT _32_ (
    .A(reset),
    .Y(_29_)
  );
  NOR _33_ (
    .A(estado[1]),
    .B(estado[2]),
    .Y(_01_)
  );
  NOR _34_ (
    .A(_01_),
    .B(valid_0),
    .Y(_02_)
  );
  NOT _35_ (
    .A(estado[0]),
    .Y(_03_)
  );
  NOT _36_ (
    .A(valid_1),
    .Y(_04_)
  );
  NAND _37_ (
    .A(estado[3]),
    .B(_04_),
    .Y(_05_)
  );
  NAND _38_ (
    .A(_05_),
    .B(_03_),
    .Y(_06_)
  );
  NOR _39_ (
    .A(_06_),
    .B(_02_),
    .Y(_07_)
  );
  NOR _40_ (
    .A(_07_),
    .B(_29_),
    .Y(_00_)
  );
  NAND _41_ (
    .A(estado[3]),
    .B(valid_1),
    .Y(_08_)
  );
  NOT _42_ (
    .A(valid_0),
    .Y(_09_)
  );
  NOR _43_ (
    .A(_01_),
    .B(_09_),
    .Y(_10_)
  );
  NOT _44_ (
    .A(_10_),
    .Y(_11_)
  );
  NAND _45_ (
    .A(_11_),
    .B(_08_),
    .Y(valid_out_e)
  );
  NOT _46_ (
    .A(_08_),
    .Y(_12_)
  );
  NAND _47_ (
    .A(_12_),
    .B(lane_1[0]),
    .Y(_13_)
  );
  NAND _48_ (
    .A(_10_),
    .B(lane_0[0]),
    .Y(_14_)
  );
  NAND _49_ (
    .A(_14_),
    .B(_13_),
    .Y(data_out_e[0])
  );
  NAND _50_ (
    .A(_12_),
    .B(lane_1[1]),
    .Y(_15_)
  );
  NAND _51_ (
    .A(_10_),
    .B(lane_0[1]),
    .Y(_16_)
  );
  NAND _52_ (
    .A(_16_),
    .B(_15_),
    .Y(data_out_e[1])
  );
  NAND _53_ (
    .A(_12_),
    .B(lane_1[2]),
    .Y(_17_)
  );
  NAND _54_ (
    .A(_10_),
    .B(lane_0[2]),
    .Y(_18_)
  );
  NAND _55_ (
    .A(_18_),
    .B(_17_),
    .Y(data_out_e[2])
  );
  NAND _56_ (
    .A(_12_),
    .B(lane_1[3]),
    .Y(_19_)
  );
  NAND _57_ (
    .A(_10_),
    .B(lane_0[3]),
    .Y(_20_)
  );
  NAND _58_ (
    .A(_20_),
    .B(_19_),
    .Y(data_out_e[3])
  );
  NAND _59_ (
    .A(_12_),
    .B(lane_1[4]),
    .Y(_21_)
  );
  NAND _60_ (
    .A(_10_),
    .B(lane_0[4]),
    .Y(_22_)
  );
  NAND _61_ (
    .A(_22_),
    .B(_21_),
    .Y(data_out_e[4])
  );
  NAND _62_ (
    .A(_12_),
    .B(lane_1[5]),
    .Y(_23_)
  );
  NAND _63_ (
    .A(_10_),
    .B(lane_0[5]),
    .Y(_24_)
  );
  NAND _64_ (
    .A(_24_),
    .B(_23_),
    .Y(data_out_e[5])
  );
  NAND _65_ (
    .A(_12_),
    .B(lane_1[6]),
    .Y(_25_)
  );
  NAND _66_ (
    .A(_10_),
    .B(lane_0[6]),
    .Y(_26_)
  );
  NAND _67_ (
    .A(_26_),
    .B(_25_),
    .Y(data_out_e[6])
  );
  NAND _68_ (
    .A(_12_),
    .B(lane_1[7]),
    .Y(_27_)
  );
  NAND _69_ (
    .A(_10_),
    .B(lane_0[7]),
    .Y(_28_)
  );
  NAND _70_ (
    .A(_28_),
    .B(_27_),
    .Y(data_out_e[7])
  );
  NOR _71_ (
    .A(_11_),
    .B(_29_),
    .Y(_30_)
  );
  NOR _72_ (
    .A(_08_),
    .B(_29_),
    .Y(_31_)
  );
  DFF _73_ (
    .C(clk_2f),
    .D(_29_),
    .Q(estado[0])
  );
  DFF _74_ (
    .C(clk_2f),
    .D(_31_),
    .Q(estado[1])
  );
  DFF _75_ (
    .C(clk_2f),
    .D(_00_),
    .Q(estado[2])
  );
  DFF _76_ (
    .C(clk_2f),
    .D(_30_),
    .Q(estado[3])
  );
endmodule
